/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:00
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SDMMC2         -----------------------------*/
#define MX_SDMMC2                              1

/* Pins */

/* SDMMC2_CMD */
#define MX_SDMMC2_CMD                          PA0
#define MX_SDMMC2_CMD_Pin                      GPIO_PIN_0
#define MX_SDMMC2_CMD_Port                     GPIOA
#define MX_SDMMC2_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC2_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC2_CMD_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_CMD_Alternate                GPIO_AF9_SDIO2

/* SDMMC2_D0 */
#define MX_SDMMC2_D0                           PB14
#define MX_SDMMC2_D0_Pin                       GPIO_PIN_14
#define MX_SDMMC2_D0_Port                      GPIOB
#define MX_SDMMC2_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D0_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D0_Alternate                 GPIO_AF9_SDIO2

/* SDMMC2_D1 */
#define MX_SDMMC2_D1                           PB15
#define MX_SDMMC2_D1_Pin                       GPIO_PIN_15
#define MX_SDMMC2_D1_Port                      GPIOB
#define MX_SDMMC2_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D1_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D1_Alternate                 GPIO_AF9_SDIO2

/* SDMMC2_D2 */
#define MX_SDMMC2_D2                           PB3
#define MX_SDMMC2_D2_Pin                       GPIO_PIN_3
#define MX_SDMMC2_D2_Port                      GPIOB
#define MX_SDMMC2_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D2_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D2_Alternate                 GPIO_AF9_SDIO2

/* SDMMC2_D3 */
#define MX_SDMMC2_D3                           PB4
#define MX_SDMMC2_D3_Pin                       GPIO_PIN_4
#define MX_SDMMC2_D3_Port                      GPIOB
#define MX_SDMMC2_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D3_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D3_Alternate                 GPIO_AF9_SDIO2

/* SDMMC2_D4 */
#define MX_SDMMC2_D4                           PB8
#define MX_SDMMC2_D4_Pin                       GPIO_PIN_8
#define MX_SDMMC2_D4_Port                      GPIOB
#define MX_SDMMC2_D4_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D4_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D4_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D4_Alternate                 GPIO_AF10_SDIO2

/* SDMMC2_D5 */
#define MX_SDMMC2_D5                           PB9
#define MX_SDMMC2_D5_Pin                       GPIO_PIN_9
#define MX_SDMMC2_D5_Port                      GPIOB
#define MX_SDMMC2_D5_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D5_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D5_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D5_Alternate                 GPIO_AF10_SDIO2

/* SDMMC2_D6 */
#define MX_SDMMC2_D6                           PC6
#define MX_SDMMC2_D6_Pin                       GPIO_PIN_6
#define MX_SDMMC2_D6_Port                      GPIOC
#define MX_SDMMC2_D6_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D6_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D6_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D6_Alternate                 GPIO_AF11_SDIO2

/* SDMMC2_D7 */
#define MX_SDMMC2_D7                           PC7
#define MX_SDMMC2_D7_Pin                       GPIO_PIN_7
#define MX_SDMMC2_D7_Port                      GPIOC
#define MX_SDMMC2_D7_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D7_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D7_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D7_Alternate                 GPIO_AF10_SDIO2

/* SDMMC2_CK */
#define MX_SDMMC2_CK                           PD6
#define MX_SDMMC2_CK_Pin                       GPIO_PIN_6
#define MX_SDMMC2_CK_Port                      GPIOD
#define MX_SDMMC2_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC2_CK_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_CK_Alternate                 GPIO_AF11_SDIO2

/*------------------------------ SPI2           -----------------------------*/
#define MX_SPI2                                1

/* Pins */

/* SPI2_SCK */
#define MX_SPI2_SCK                            PI1
#define MX_SPI2_SCK_Pin                        GPIO_PIN_1
#define MX_SPI2_SCK_Port                       GPIOI
#define MX_SPI2_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI2_SCK_Pull                       GPIO_NOPULL
#define MX_SPI2_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI2_SCK_Alternate                  GPIO_AF5_SPI2

/* SPI2_MISO */
#define MX_SPI2_MISO                           PI2
#define MX_SPI2_MISO_Pin                       GPIO_PIN_2
#define MX_SPI2_MISO_Port                      GPIOI
#define MX_SPI2_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MISO_Pull                      GPIO_NOPULL
#define MX_SPI2_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MISO_Alternate                 GPIO_AF5_SPI2

/* SPI2_MOSI */
#define MX_SPI2_MOSI                           PI3
#define MX_SPI2_MOSI_Pin                       GPIO_PIN_3
#define MX_SPI2_MOSI_Port                      GPIOI
#define MX_SPI2_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI2_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MOSI_Alternate                 GPIO_AF5_SPI2

/*------------------------------ UART7          -----------------------------*/
#define MX_UART7                               1

/* Pins */

/* UART7_TX */
#define MX_UART7_TX                            PA15
#define MX_UART7_TX_Pin                        GPIO_PIN_15
#define MX_UART7_TX_Port                       GPIOA
#define MX_UART7_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART7_TX_Pull                       GPIO_NOPULL
#define MX_UART7_TX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART7_TX_Alternate                  GPIO_AF11_UART7

/* UART7_RX */
#define MX_UART7_RX                            PA8
#define MX_UART7_RX_Pin                        GPIO_PIN_8
#define MX_UART7_RX_Port                       GPIOA
#define MX_UART7_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART7_RX_Pull                       GPIO_NOPULL
#define MX_UART7_RX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART7_RX_Alternate                  GPIO_AF11_UART7

/*------------------------------ FDCAN2         -----------------------------*/
#define MX_FDCAN2                              1

/* Pins */

/* FDCAN2_TX */
#define MX_FDCAN2_TX                           PB13
#define MX_FDCAN2_TX_Pin                       GPIO_PIN_13
#define MX_FDCAN2_TX_Port                      GPIOB
#define MX_FDCAN2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN2_TX_Pull                      GPIO_NOPULL
#define MX_FDCAN2_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN2_TX_Alternate                 GPIO_AF9_FDCAN2

/* FDCAN2_RX */
#define MX_FDCAN2_RX                           PB5
#define MX_FDCAN2_RX_Pin                       GPIO_PIN_5
#define MX_FDCAN2_RX_Port                      GPIOB
#define MX_FDCAN2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN2_RX_Pull                      GPIO_NOPULL
#define MX_FDCAN2_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN2_RX_Alternate                 GPIO_AF9_FDCAN2

/*------------------------------ I2C2           -----------------------------*/
#define MX_I2C2                                1

/* Pins */

/* I2C2_SDA */
#define MX_I2C2_SDA                            PF0
#define MX_I2C2_SDA_Pin                        GPIO_PIN_0
#define MX_I2C2_SDA_Port                       GPIOF
#define MX_I2C2_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SDA_Pull                       GPIO_NOPULL
#define MX_I2C2_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SDA_Alternate                  GPIO_AF4_I2C2

/* I2C2_SCL */
#define MX_I2C2_SCL                            PF1
#define MX_I2C2_SCL_Pin                        GPIO_PIN_1
#define MX_I2C2_SCL_Port                       GPIOF
#define MX_I2C2_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SCL_Pull                       GPIO_NOPULL
#define MX_I2C2_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SCL_Alternate                  GPIO_AF4_I2C2

#endif  /* __MX_DEVICE_H */
