/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:57
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SDMMC2         -----------------------------*/
#define MX_SDMMC2                              1

/* Pins */

/* SDMMC2_D0 */
#define MX_SDMMC2_D0                           PB14
#define MX_SDMMC2_D0_Pin                       GPIO_PIN_14
#define MX_SDMMC2_D0_Port                      GPIOB
#define MX_SDMMC2_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D0_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D0_Alternate                 GPIO_AF9_SDMMC2

/* SDMMC2_D2 */
#define MX_SDMMC2_D2                           PB3_JTDO_TRACESWO_

/* SDMMC2_CK */
#define MX_SDMMC2_CK                           PD6
#define MX_SDMMC2_CK_Pin                       GPIO_PIN_6
#define MX_SDMMC2_CK_Port                      GPIOD
#define MX_SDMMC2_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC2_CK_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_CK_Alternate                 GPIO_AF11_SDMMC2

/* SDMMC2_CMD */
#define MX_SDMMC2_CMD                          PD7
#define MX_SDMMC2_CMD_Pin                      GPIO_PIN_7
#define MX_SDMMC2_CMD_Port                     GPIOD
#define MX_SDMMC2_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC2_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC2_CMD_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_CMD_Alternate                GPIO_AF11_SDMMC2

/* SDMMC2_D1 */
#define MX_SDMMC2_D1                           PG10
#define MX_SDMMC2_D1_Pin                       GPIO_PIN_10
#define MX_SDMMC2_D1_Port                      GPIOG
#define MX_SDMMC2_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D1_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D1_Alternate                 GPIO_AF11_SDMMC2

/* SDMMC2_D3 */
#define MX_SDMMC2_D3                           PG12
#define MX_SDMMC2_D3_Pin                       GPIO_PIN_12
#define MX_SDMMC2_D3_Port                      GPIOG
#define MX_SDMMC2_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D3_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D3_Alternate                 GPIO_AF10_SDMMC2

/*------------------------------ SPI2           -----------------------------*/
#define MX_SPI2                                1

/* Pins */

/* SPI2_SCK */
#define MX_SPI2_SCK                            PD3
#define MX_SPI2_SCK_Pin                        GPIO_PIN_3
#define MX_SPI2_SCK_Port                       GPIOD
#define MX_SPI2_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI2_SCK_Pull                       GPIO_NOPULL
#define MX_SPI2_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI2_SCK_Alternate                  GPIO_AF5_SPI2

/* SPI2_MISO */
#define MX_SPI2_MISO                           PI2
#define MX_SPI2_MISO_Pin                       GPIO_PIN_2
#define MX_SPI2_MISO_Port                      GPIOI
#define MX_SPI2_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MISO_Pull                      GPIO_NOPULL
#define MX_SPI2_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MISO_Alternate                 GPIO_AF5_SPI2

/* SPI2_MOSI */
#define MX_SPI2_MOSI                           PI3
#define MX_SPI2_MOSI_Pin                       GPIO_PIN_3
#define MX_SPI2_MOSI_Port                      GPIOI
#define MX_SPI2_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI2_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MOSI_Alternate                 GPIO_AF5_SPI2

/*------------------------------ USART6         -----------------------------*/
#define MX_USART6                              1

/* Virtual mode */
#define MX_USART6_VM                           VM_ASYNC

/* Pins */

/* USART6_TX */
#define MX_USART6_TX                           PG14
#define MX_USART6_TX_Pin                       GPIO_PIN_14
#define MX_USART6_TX_Port                      GPIOG
#define MX_USART6_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART6_TX_Pull                      GPIO_NOPULL
#define MX_USART6_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART6_TX_Alternate                 GPIO_AF7_USART6

/* USART6_RX */
#define MX_USART6_RX                           PG9
#define MX_USART6_RX_Pin                       GPIO_PIN_9
#define MX_USART6_RX_Port                      GPIOG
#define MX_USART6_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART6_RX_Pull                      GPIO_NOPULL
#define MX_USART6_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART6_RX_Alternate                 GPIO_AF7_USART6

/*------------------------------ USB            -----------------------------*/
#define MX_USB                                 1

/* Virtual mode */
#define MX_USB_VM                              Device_Only

/* Pins */

/* USB_DM */
#define MX_USB_DM                              PA11

/* USB_DP */
#define MX_USB_DP                              PA12

/*------------------------------ FDCAN1         -----------------------------*/
#define MX_FDCAN1                              1

/* Pins */

/* FDCAN1_TX */
#define MX_FDCAN1_TX                           PD5
#define MX_FDCAN1_TX_Pin                       GPIO_PIN_5
#define MX_FDCAN1_TX_Port                      GPIOD
#define MX_FDCAN1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_TX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_TX_Alternate                 GPIO_AF9_FDCAN1

/* FDCAN1_RX */
#define MX_FDCAN1_RX                           PE0
#define MX_FDCAN1_RX_Pin                       GPIO_PIN_0
#define MX_FDCAN1_RX_Port                      GPIOE
#define MX_FDCAN1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_RX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_RX_Alternate                 GPIO_AF9_FDCAN1

/*------------------------------ I2C2           -----------------------------*/
#define MX_I2C2                                1

/* Pins */

/* I2C2_SDA */
#define MX_I2C2_SDA                            PF0
#define MX_I2C2_SDA_Pin                        GPIO_PIN_0
#define MX_I2C2_SDA_Port                       GPIOF
#define MX_I2C2_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SDA_Pull                       GPIO_NOPULL
#define MX_I2C2_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SDA_Alternate                  GPIO_AF4_I2C2

/* I2C2_SCL */
#define MX_I2C2_SCL                            PF1
#define MX_I2C2_SCL_Pin                        GPIO_PIN_1
#define MX_I2C2_SCL_Port                       GPIOF
#define MX_I2C2_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SCL_Pull                       GPIO_NOPULL
#define MX_I2C2_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SCL_Alternate                  GPIO_AF4_I2C2

#endif  /* __MX_DEVICE_H */
