/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:05
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB8
#define MX_I2C1_SCL_Pin                        GPIO_PIN_8
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB9
#define MX_I2C1_SDA_Pin                        GPIO_PIN_9
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ I2C3           -----------------------------*/
#define MX_I2C3                                1

/* Pins */

/* I2C3_SCL */
#define MX_I2C3_SCL                            PC0
#define MX_I2C3_SCL_Pin                        GPIO_PIN_0
#define MX_I2C3_SCL_Port                       GPIOC
#define MX_I2C3_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SCL_Pull                       GPIO_NOPULL
#define MX_I2C3_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SCL_Alternate                  GPIO_AF4_I2C3

/* I2C3_SDA */
#define MX_I2C3_SDA                            PC1
#define MX_I2C3_SDA_Pin                        GPIO_PIN_1
#define MX_I2C3_SDA_Port                       GPIOC
#define MX_I2C3_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SDA_Pull                       GPIO_NOPULL
#define MX_I2C3_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SDA_Alternate                  GPIO_AF4_I2C3

/*------------------------------ USB            -----------------------------*/
#define MX_USB                                 1

/* Pins */

/* USB_DM */
#define MX_USB_DM                              PA11
#define MX_USB_DM_Pin                          GPIO_PIN_11
#define MX_USB_DM_Port                         GPIOA
#define MX_USB_DM_Mode                         GPIO_MODE_AF_PP
#define MX_USB_DM_Pull                         GPIO_NOPULL
#define MX_USB_DM_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_USB_DM_Alternate                    GPIO_AF10_USB

/* USB_DP */
#define MX_USB_DP                              PA12
#define MX_USB_DP_Pin                          GPIO_PIN_12
#define MX_USB_DP_Port                         GPIOA
#define MX_USB_DP_Mode                         GPIO_MODE_AF_PP
#define MX_USB_DP_Pull                         GPIO_NOPULL
#define MX_USB_DP_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_USB_DP_Alternate                    GPIO_AF10_USB

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_TX */
#define MX_LPUART1_TX                          PA2
#define MX_LPUART1_TX_Pin                      GPIO_PIN_2
#define MX_LPUART1_TX_Port                     GPIOA
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Alternate                GPIO_AF8_LPUART1

/* LPUART1_RX */
#define MX_LPUART1_RX                          PA3
#define MX_LPUART1_RX_Pin                      GPIO_PIN_3
#define MX_LPUART1_RX_Port                     GPIOA
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Alternate                GPIO_AF8_LPUART1

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_SCK */
#define MX_SPI1_SCK                            PA1
#define MX_SPI1_SCK_Pin                        GPIO_PIN_1
#define MX_SPI1_SCK_Port                       GPIOA
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/* SPI1_MISO */
#define MX_SPI1_MISO                           PA6
#define MX_SPI1_MISO_Pin                       GPIO_PIN_6
#define MX_SPI1_MISO_Port                      GPIOA
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MISO_Alternate                 GPIO_AF5_SPI1

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PA7
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_7
#define MX_SPI1_MOSI_Port                      GPIOA
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/*------------------------------ SPI2           -----------------------------*/
#define MX_SPI2                                1

/* Pins */

/* SPI2_SCK */
#define MX_SPI2_SCK                            PB10
#define MX_SPI2_SCK_Pin                        GPIO_PIN_10
#define MX_SPI2_SCK_Port                       GPIOB
#define MX_SPI2_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI2_SCK_Pull                       GPIO_NOPULL
#define MX_SPI2_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI2_SCK_Alternate                  GPIO_AF5_SPI2

/* SPI2_MISO */
#define MX_SPI2_MISO                           PC2
#define MX_SPI2_MISO_Pin                       GPIO_PIN_2
#define MX_SPI2_MISO_Port                      GPIOC
#define MX_SPI2_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MISO_Pull                      GPIO_NOPULL
#define MX_SPI2_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MISO_Alternate                 GPIO_AF5_SPI2

/* SPI2_MOSI */
#define MX_SPI2_MOSI                           PC3
#define MX_SPI2_MOSI_Pin                       GPIO_PIN_3
#define MX_SPI2_MOSI_Port                      GPIOC
#define MX_SPI2_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI2_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI2_MOSI_Alternate                 GPIO_AF5_SPI2

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_ASYNC

/* Pins */

/* USART1_RX */
#define MX_USART1_RX                           PA10
#define MX_USART1_RX_Pin                       GPIO_PIN_10
#define MX_USART1_RX_Port                      GPIOA
#define MX_USART1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_RX_Pull                      GPIO_NOPULL
#define MX_USART1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Alternate                 GPIO_AF7_USART1

/* USART1_TX */
#define MX_USART1_TX                           PA9
#define MX_USART1_TX_Pin                       GPIO_PIN_9
#define MX_USART1_TX_Port                      GPIOA
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_TX_Pull                      GPIO_NOPULL
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Alternate                 GPIO_AF7_USART1

#endif  /* __MX_DEVICE_H */
