/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:53
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ CAN            -----------------------------*/
#define MX_CAN                                 1

/* Pins */

/* CAN_RX */
#define MX_CAN_RX                              PD0
#define MX_CAN_RX_Pin                          GPIO_PIN_0
#define MX_CAN_RX_Port                         GPIOD
#define MX_CAN_RX_Mode                         GPIO_MODE_AF_PP
#define MX_CAN_RX_Pull                         GPIO_NOPULL
#define MX_CAN_RX_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_CAN_RX_Alternate                    GPIO_AF0_CAN

/* CAN_TX */
#define MX_CAN_TX                              PD1
#define MX_CAN_TX_Pin                          GPIO_PIN_1
#define MX_CAN_TX_Port                         GPIOD
#define MX_CAN_TX_Mode                         GPIO_MODE_AF_PP
#define MX_CAN_TX_Pull                         GPIO_NOPULL
#define MX_CAN_TX_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_CAN_TX_Alternate                    GPIO_AF0_CAN

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_SMARTCARD

/* Pins */

/* USART1_CK */
#define MX_USART1_CK                           PA8
#define MX_USART1_CK_Pin                       GPIO_PIN_8
#define MX_USART1_CK_Port                      GPIOA
#define MX_USART1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_CK_Pull                      GPIO_NOPULL
#define MX_USART1_CK_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_CK_Alternate                 GPIO_AF1_USART1

/* USART1_TX */
#define MX_USART1_TX                           PA9
#define MX_USART1_TX_Pin                       GPIO_PIN_9
#define MX_USART1_TX_Port                      GPIOA
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_OD
#define MX_USART1_TX_Pull                      GPIO_PULLUP
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Alternate                 GPIO_AF1_USART1

/*------------------------------ USART2         -----------------------------*/
#define MX_USART2                              1

/* Virtual mode */
#define MX_USART2_VM                           VM_ASYNC

/* Pins */

/* USART2_CTS */
#define MX_USART2_CTS                          PD3
#define MX_USART2_CTS_Pin                      GPIO_PIN_3
#define MX_USART2_CTS_Port                     GPIOD
#define MX_USART2_CTS_Mode                     GPIO_MODE_AF_PP
#define MX_USART2_CTS_Pull                     GPIO_NOPULL
#define MX_USART2_CTS_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_USART2_CTS_Alternate                GPIO_AF0_USART2

/* USART2_RTS */
#define MX_USART2_RTS                          PD4
#define MX_USART2_RTS_Pin                      GPIO_PIN_4
#define MX_USART2_RTS_Port                     GPIOD
#define MX_USART2_RTS_Mode                     GPIO_MODE_AF_PP
#define MX_USART2_RTS_Pull                     GPIO_NOPULL
#define MX_USART2_RTS_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_USART2_RTS_Alternate                GPIO_AF0_USART2

/* USART2_TX */
#define MX_USART2_TX                           PD5
#define MX_USART2_TX_Pin                       GPIO_PIN_5
#define MX_USART2_TX_Port                      GPIOD
#define MX_USART2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_TX_Pull                      GPIO_NOPULL
#define MX_USART2_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Alternate                 GPIO_AF0_USART2

/* USART2_RX */
#define MX_USART2_RX                           PD6
#define MX_USART2_RX_Pin                       GPIO_PIN_6
#define MX_USART2_RX_Port                      GPIOD
#define MX_USART2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_RX_Pull                      GPIO_NOPULL
#define MX_USART2_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Alternate                 GPIO_AF0_USART2

/*------------------------------ USB            -----------------------------*/
#define MX_USB                                 1

/* Pins */

/* USB_DM */
#define MX_USB_DM                              PA11

/* USB_DP */
#define MX_USB_DP                              PA12

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB6

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB7

/*------------------------------ I2C2           -----------------------------*/
#define MX_I2C2                                1

/* Pins */

/* I2C2_SCL */
#define MX_I2C2_SCL                            PB13
#define MX_I2C2_SCL_Pin                        GPIO_PIN_13
#define MX_I2C2_SCL_Port                       GPIOB
#define MX_I2C2_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SCL_Pull                       GPIO_PULLUP
#define MX_I2C2_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SCL_Alternate                  GPIO_AF5_I2C2

/* I2C2_SDA */
#define MX_I2C2_SDA                            PB14
#define MX_I2C2_SDA_Pin                        GPIO_PIN_14
#define MX_I2C2_SDA_Port                       GPIOB
#define MX_I2C2_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SDA_Pull                       GPIO_PULLUP
#define MX_I2C2_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SDA_Alternate                  GPIO_AF5_I2C2

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_SCK */
#define MX_SPI1_SCK                            PB3
#define MX_SPI1_SCK_Pin                        GPIO_PIN_3
#define MX_SPI1_SCK_Port                       GPIOB
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Alternate                  GPIO_AF0_SPI1

/* SPI1_MISO */
#define MX_SPI1_MISO                           PE14
#define MX_SPI1_MISO_Pin                       GPIO_PIN_14
#define MX_SPI1_MISO_Port                      GPIOE
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MISO_Alternate                 GPIO_AF1_SPI1

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PE15
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_15
#define MX_SPI1_MOSI_Port                      GPIOE
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Alternate                 GPIO_AF1_SPI1

#endif  /* __MX_DEVICE_H */
