/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:04
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB6
#define MX_I2C1_SCL_Pin                        GPIO_PIN_6
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB7
#define MX_I2C1_SDA_Pin                        GPIO_PIN_7
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ USART3         -----------------------------*/
#define MX_USART3                              1

/* Virtual mode */
#define MX_USART3_VM                           VM_ASYNC

/* Pins */

/* USART3_TX */
#define MX_USART3_TX                           PB10
#define MX_USART3_TX_Pin                       GPIO_PIN_10
#define MX_USART3_TX_Port                      GPIOB
#define MX_USART3_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_TX_Pull                      GPIO_NOPULL
#define MX_USART3_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART3_TX_Alternate                 GPIO_AF7_USART3

/* USART3_RX */
#define MX_USART3_RX                           PC5
#define MX_USART3_RX_Pin                       GPIO_PIN_5
#define MX_USART3_RX_Port                      GPIOC
#define MX_USART3_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_RX_Pull                      GPIO_NOPULL
#define MX_USART3_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART3_RX_Alternate                 GPIO_AF7_USART3

/*------------------------------ USB            -----------------------------*/
#define MX_USB                                 1

/* Pins */

/* USB_DM */
#define MX_USB_DM                              PA11
#define MX_USB_DM_Pin                          GPIO_PIN_11
#define MX_USB_DM_Port                         GPIOA
#define MX_USB_DM_Mode                         GPIO_MODE_AF_PP
#define MX_USB_DM_Pull                         GPIO_NOPULL
#define MX_USB_DM_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_USB_DM_Alternate                    GPIO_AF10_USB

/* USB_DP */
#define MX_USB_DP                              PA12
#define MX_USB_DP_Pin                          GPIO_PIN_12
#define MX_USB_DP_Port                         GPIOA
#define MX_USB_DP_Mode                         GPIO_MODE_AF_PP
#define MX_USB_DP_Pull                         GPIO_NOPULL
#define MX_USB_DP_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_USB_DP_Alternate                    GPIO_AF10_USB

#endif  /* __MX_DEVICE_H */
