/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:03
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ CAN1           -----------------------------*/
#define MX_CAN1                                1

/* Pins */

/* CAN1_TX */
#define MX_CAN1_TX                             PD1
#define MX_CAN1_TX_Pin                         GPIO_PIN_1
#define MX_CAN1_TX_Port                        GPIOD
#define MX_CAN1_TX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN1_TX_Pull                        GPIO_NOPULL
#define MX_CAN1_TX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_TX_Alternate                   GPIO_AF9_CAN1

/* CAN1_RX */
#define MX_CAN1_RX                             PI9
#define MX_CAN1_RX_Pin                         GPIO_PIN_9
#define MX_CAN1_RX_Port                        GPIOI
#define MX_CAN1_RX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN1_RX_Pull                        GPIO_NOPULL
#define MX_CAN1_RX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_RX_Alternate                   GPIO_AF9_CAN1

/*------------------------------ I2C2           -----------------------------*/
#define MX_I2C2                                1

/* Pins */

/* I2C2_SDA */
#define MX_I2C2_SDA                            PF0
#define MX_I2C2_SDA_Pin                        GPIO_PIN_0
#define MX_I2C2_SDA_Port                       GPIOF
#define MX_I2C2_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SDA_Pull                       GPIO_NOPULL
#define MX_I2C2_SDA_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SDA_Alternate                  GPIO_AF4_I2C2

/* I2C2_SCL */
#define MX_I2C2_SCL                            PF1
#define MX_I2C2_SCL_Pin                        GPIO_PIN_1
#define MX_I2C2_SCL_Port                       GPIOF
#define MX_I2C2_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SCL_Pull                       GPIO_NOPULL
#define MX_I2C2_SCL_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SCL_Alternate                  GPIO_AF4_I2C2

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_TX */
#define MX_LPUART1_TX                          PG7
#define MX_LPUART1_TX_Pin                      GPIO_PIN_7
#define MX_LPUART1_TX_Port                     GPIOG
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_LPUART1_TX_Alternate                GPIO_AF8_LPUART1

/* LPUART1_RX */
#define MX_LPUART1_RX                          PG8
#define MX_LPUART1_RX_Pin                      GPIO_PIN_8
#define MX_LPUART1_RX_Port                     GPIOG
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_LPUART1_RX_Alternate                GPIO_AF8_LPUART1

/*------------------------------ SDMMC1         -----------------------------*/
#define MX_SDMMC1                              1

/* Pins */

/* SDMMC1_CKIN */
#define MX_SDMMC1_CKIN                         PB8
#define MX_SDMMC1_CKIN_Pin                     GPIO_PIN_8
#define MX_SDMMC1_CKIN_Port                    GPIOB
#define MX_SDMMC1_CKIN_Mode                    GPIO_MODE_AF_PP
#define MX_SDMMC1_CKIN_Pull                    GPIO_NOPULL
#define MX_SDMMC1_CKIN_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CKIN_Alternate               GPIO_AF8_SDMMC1

/* SDMMC1_CDIR */
#define MX_SDMMC1_CDIR                         PB9
#define MX_SDMMC1_CDIR_Pin                     GPIO_PIN_9
#define MX_SDMMC1_CDIR_Port                    GPIOB
#define MX_SDMMC1_CDIR_Mode                    GPIO_MODE_AF_PP
#define MX_SDMMC1_CDIR_Pull                    GPIO_NOPULL
#define MX_SDMMC1_CDIR_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CDIR_Alternate               GPIO_AF8_SDMMC1

/* SDMMC1_D2 */
#define MX_SDMMC1_D2                           PC10
#define MX_SDMMC1_D2_Pin                       GPIO_PIN_10
#define MX_SDMMC1_D2_Port                      GPIOC
#define MX_SDMMC1_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D2_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D2_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D3 */
#define MX_SDMMC1_D3                           PC11
#define MX_SDMMC1_D3_Pin                       GPIO_PIN_11
#define MX_SDMMC1_D3_Port                      GPIOC
#define MX_SDMMC1_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D3_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D3_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CK */
#define MX_SDMMC1_CK                           PC12
#define MX_SDMMC1_CK_Pin                       GPIO_PIN_12
#define MX_SDMMC1_CK_Port                      GPIOC
#define MX_SDMMC1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC1_CK_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CK_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D0DIR */
#define MX_SDMMC1_D0DIR                        PC6
#define MX_SDMMC1_D0DIR_Pin                    GPIO_PIN_6
#define MX_SDMMC1_D0DIR_Port                   GPIOC
#define MX_SDMMC1_D0DIR_Mode                   GPIO_MODE_AF_PP
#define MX_SDMMC1_D0DIR_Pull                   GPIO_NOPULL
#define MX_SDMMC1_D0DIR_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D0DIR_Alternate              GPIO_AF8_SDMMC1

/* SDMMC1_D123DIR */
#define MX_SDMMC1_D123DIR                      PC7
#define MX_SDMMC1_D123DIR_Pin                  GPIO_PIN_7
#define MX_SDMMC1_D123DIR_Port                 GPIOC
#define MX_SDMMC1_D123DIR_Mode                 GPIO_MODE_AF_PP
#define MX_SDMMC1_D123DIR_Pull                 GPIO_NOPULL
#define MX_SDMMC1_D123DIR_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D123DIR_Alternate            GPIO_AF8_SDMMC1

/* SDMMC1_D0 */
#define MX_SDMMC1_D0                           PC8
#define MX_SDMMC1_D0_Pin                       GPIO_PIN_8
#define MX_SDMMC1_D0_Port                      GPIOC
#define MX_SDMMC1_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D0_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D0_Alternate                 GPIO_AF8_SDMMC1

/* SDMMC1_D1 */
#define MX_SDMMC1_D1                           PC9
#define MX_SDMMC1_D1_Pin                       GPIO_PIN_9
#define MX_SDMMC1_D1_Port                      GPIOC
#define MX_SDMMC1_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D1_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D1_Alternate                 GPIO_AF8_SDMMC1

/* SDMMC1_CMD */
#define MX_SDMMC1_CMD                          PD2
#define MX_SDMMC1_CMD_Pin                      GPIO_PIN_2
#define MX_SDMMC1_CMD_Port                     GPIOD
#define MX_SDMMC1_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC1_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC1_CMD_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CMD_Alternate                GPIO_AF12_SDMMC1

/*------------------------------ UART4          -----------------------------*/
#define MX_UART4                               1

/* Pins */

/* UART4_TX */
#define MX_UART4_TX                            PA0
#define MX_UART4_TX_Pin                        GPIO_PIN_0
#define MX_UART4_TX_Port                       GPIOA
#define MX_UART4_TX_Mode                       GPIO_MODE_AF_OD
#define MX_UART4_TX_Pull                       GPIO_PULLUP
#define MX_UART4_TX_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_TX_Alternate                  GPIO_AF8_UART4

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_ASYNC

/* Pins */

/* USART1_RX */
#define MX_USART1_RX                           PB7
#define MX_USART1_RX_Pin                       GPIO_PIN_7
#define MX_USART1_RX_Port                      GPIOB
#define MX_USART1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_RX_Pull                      GPIO_NOPULL
#define MX_USART1_RX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Alternate                 GPIO_AF7_USART1

/* USART1_TX */
#define MX_USART1_TX                           PG9
#define MX_USART1_TX_Pin                       GPIO_PIN_9
#define MX_USART1_TX_Port                      GPIOG
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_TX_Pull                      GPIO_NOPULL
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Alternate                 GPIO_AF7_USART1

/*------------------------------ USB_OTG_FS     -----------------------------*/
#define MX_USB_OTG_FS                          1

/* Pins */

/* USB_OTG_FS_ID */
#define MX_USB_OTG_FS_ID                       PA10

/* USB_OTG_FS_DM */
#define MX_USB_OTG_FS_DM                       PA11

/* USB_OTG_FS_DP */
#define MX_USB_OTG_FS_DP                       PA12

#endif  /* __MX_DEVICE_H */
