/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:05
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SDMMC2         -----------------------------*/
#define MX_SDMMC2                              1

/* Pins */

/* SDMMC2_D0 */
#define MX_SDMMC2_D0                           PB14
#define MX_SDMMC2_D0_Pin                       GPIO_PIN_14
#define MX_SDMMC2_D0_Port                      GPIOB
#define MX_SDMMC2_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D0_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D0_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_D1 */
#define MX_SDMMC2_D1                           PB15
#define MX_SDMMC2_D1_Pin                       GPIO_PIN_15
#define MX_SDMMC2_D1_Port                      GPIOB
#define MX_SDMMC2_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D1_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D1_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_D2 */
#define MX_SDMMC2_D2                           PB3
#define MX_SDMMC2_D2_Pin                       GPIO_PIN_3
#define MX_SDMMC2_D2_Port                      GPIOB
#define MX_SDMMC2_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D2_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D2_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_D3 */
#define MX_SDMMC2_D3                           PB4
#define MX_SDMMC2_D3_Pin                       GPIO_PIN_4
#define MX_SDMMC2_D3_Port                      GPIOB
#define MX_SDMMC2_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D3_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D3_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_CK */
#define MX_SDMMC2_CK                           PD6
#define MX_SDMMC2_CK_Pin                       GPIO_PIN_6
#define MX_SDMMC2_CK_Port                      GPIOD
#define MX_SDMMC2_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC2_CK_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_CK_Alternate                 GPIO_AF11_SDMMC2

/* SDMMC2_CMD */
#define MX_SDMMC2_CMD                          PD7
#define MX_SDMMC2_CMD_Pin                      GPIO_PIN_7
#define MX_SDMMC2_CMD_Port                     GPIOD
#define MX_SDMMC2_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC2_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC2_CMD_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_CMD_Alternate                GPIO_AF11_SDMMC2

/*------------------------------ USART2         -----------------------------*/
#define MX_USART2                              1

/* Virtual mode */
#define MX_USART2_VM                           VM_ASYNC

/* Pins */

/* USART2_RX */
#define MX_USART2_RX                           PA15
#define MX_USART2_RX_Pin                       GPIO_PIN_15
#define MX_USART2_RX_Port                      GPIOA
#define MX_USART2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_RX_Pull                      GPIO_NOPULL
#define MX_USART2_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Alternate                 GPIO_AF3_USART2

/* USART2_TX */
#define MX_USART2_TX                           PD5
#define MX_USART2_TX_Pin                       GPIO_PIN_5
#define MX_USART2_TX_Port                      GPIOD
#define MX_USART2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_TX_Pull                      GPIO_NOPULL
#define MX_USART2_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Alternate                 GPIO_AF7_USART2

/*------------------------------ I2C2           -----------------------------*/
#define MX_I2C2                                1

/* Pins */

/* I2C2_SDA */
#define MX_I2C2_SDA                            PF0
#define MX_I2C2_SDA_Pin                        GPIO_PIN_0
#define MX_I2C2_SDA_Port                       GPIOF
#define MX_I2C2_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SDA_Pull                       GPIO_NOPULL
#define MX_I2C2_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SDA_Alternate                  GPIO_AF4_I2C2

/* I2C2_SCL */
#define MX_I2C2_SCL                            PH4
#define MX_I2C2_SCL_Pin                        GPIO_PIN_4
#define MX_I2C2_SCL_Port                       GPIOH
#define MX_I2C2_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C2_SCL_Pull                       GPIO_NOPULL
#define MX_I2C2_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SCL_Alternate                  GPIO_AF4_I2C2

#endif  /* __MX_DEVICE_H */
