/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:55
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ FDCAN1         -----------------------------*/
#define MX_FDCAN1                              1

/* Pins */

/* FDCAN1_RX */
#define MX_FDCAN1_RX                           PD0
#define MX_FDCAN1_RX_Pin                       GPIO_PIN_0
#define MX_FDCAN1_RX_Port                      GPIOD
#define MX_FDCAN1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_RX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_RX_Alternate                 GPIO_AF9_FDCAN1

/* FDCAN1_TX */
#define MX_FDCAN1_TX                           PD1
#define MX_FDCAN1_TX_Pin                       GPIO_PIN_1
#define MX_FDCAN1_TX_Port                      GPIOD
#define MX_FDCAN1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_TX_Pull                      GPIO_PULLUP
#define MX_FDCAN1_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FDCAN1_TX_Alternate                 GPIO_AF9_FDCAN1

/*------------------------------ FDCAN2         -----------------------------*/
#define MX_FDCAN2                              1

/* Pins */

/* FDCAN2_RX */
#define MX_FDCAN2_RX                           PB5
#define MX_FDCAN2_RX_Pin                       GPIO_PIN_5
#define MX_FDCAN2_RX_Port                      GPIOB
#define MX_FDCAN2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN2_RX_Pull                      GPIO_NOPULL
#define MX_FDCAN2_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN2_RX_Alternate                 GPIO_AF9_FDCAN2

/* FDCAN2_TX */
#define MX_FDCAN2_TX                           PB6
#define MX_FDCAN2_TX_Pin                       GPIO_PIN_6
#define MX_FDCAN2_TX_Port                      GPIOB
#define MX_FDCAN2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN2_TX_Pull                      GPIO_NOPULL
#define MX_FDCAN2_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN2_TX_Alternate                 GPIO_AF9_FDCAN2

/*------------------------------ UART4          -----------------------------*/
#define MX_UART4                               1

/* Pins */

/* UART4_TX */
#define MX_UART4_TX                            PC10
#define MX_UART4_TX_Pin                        GPIO_PIN_10
#define MX_UART4_TX_Port                       GPIOC
#define MX_UART4_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_TX_Pull                       GPIO_NOPULL
#define MX_UART4_TX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_TX_Alternate                  GPIO_AF5_UART4

/* UART4_RX */
#define MX_UART4_RX                            PC11
#define MX_UART4_RX_Pin                        GPIO_PIN_11
#define MX_UART4_RX_Port                       GPIOC
#define MX_UART4_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_RX_Pull                       GPIO_NOPULL
#define MX_UART4_RX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_RX_Alternate                  GPIO_AF5_UART4

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_ASYNC

/* Pins */

/* USART1_TX */
#define MX_USART1_TX                           PE0
#define MX_USART1_TX_Pin                       GPIO_PIN_0
#define MX_USART1_TX_Port                      GPIOE
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_TX_Pull                      GPIO_NOPULL
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Alternate                 GPIO_AF7_USART1

/* USART1_RX */
#define MX_USART1_RX                           PE1
#define MX_USART1_RX_Pin                       GPIO_PIN_1
#define MX_USART1_RX_Port                      GPIOE
#define MX_USART1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_RX_Pull                      GPIO_NOPULL
#define MX_USART1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Alternate                 GPIO_AF7_USART1

/*------------------------------ USB            -----------------------------*/
#define MX_USB                                 1

/* Pins */

/* USB_DM */
#define MX_USB_DM                              PA11

/* USB_DP */
#define MX_USB_DP                              PA12

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB8
#define MX_I2C1_SCL_Pin                        GPIO_PIN_8
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB9
#define MX_I2C1_SDA_Pin                        GPIO_PIN_9
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ I2C3           -----------------------------*/
#define MX_I2C3                                1

/* Pins */

/* I2C3_SCL */
#define MX_I2C3_SCL                            PC8
#define MX_I2C3_SCL_Pin                        GPIO_PIN_8
#define MX_I2C3_SCL_Port                       GPIOC
#define MX_I2C3_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SCL_Pull                       GPIO_NOPULL
#define MX_I2C3_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SCL_Alternate                  GPIO_AF8_I2C3

/* I2C3_SDA */
#define MX_I2C3_SDA                            PC9
#define MX_I2C3_SDA_Pin                        GPIO_PIN_9
#define MX_I2C3_SDA_Port                       GPIOC
#define MX_I2C3_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SDA_Pull                       GPIO_NOPULL
#define MX_I2C3_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SDA_Alternate                  GPIO_AF8_I2C3

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_RX */
#define MX_LPUART1_RX                          PC0
#define MX_LPUART1_RX_Pin                      GPIO_PIN_0
#define MX_LPUART1_RX_Port                     GPIOC
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Alternate                GPIO_AF8_LPUART1

/* LPUART1_TX */
#define MX_LPUART1_TX                          PC1
#define MX_LPUART1_TX_Pin                      GPIO_PIN_1
#define MX_LPUART1_TX_Port                     GPIOC
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Alternate                GPIO_AF8_LPUART1

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PA7
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_7
#define MX_SPI1_MOSI_Port                      GPIOA
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/* SPI1_SCK */
#define MX_SPI1_SCK                            PB3
#define MX_SPI1_SCK_Pin                        GPIO_PIN_3
#define MX_SPI1_SCK_Port                       GPIOB
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/* SPI1_MISO */
#define MX_SPI1_MISO                           PB4
#define MX_SPI1_MISO_Pin                       GPIO_PIN_4
#define MX_SPI1_MISO_Port                      GPIOB
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MISO_Alternate                 GPIO_AF5_SPI1

/*------------------------------ SPI4           -----------------------------*/
#define MX_SPI4                                1

/* Pins */

/* SPI4_SCK */
#define MX_SPI4_SCK                            PE2
#define MX_SPI4_SCK_Pin                        GPIO_PIN_2
#define MX_SPI4_SCK_Port                       GPIOE
#define MX_SPI4_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI4_SCK_Pull                       GPIO_PULLUP
#define MX_SPI4_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI4_SCK_Alternate                  GPIO_AF5_SPI4

/* SPI4_MISO */
#define MX_SPI4_MISO                           PE5
#define MX_SPI4_MISO_Pin                       GPIO_PIN_5
#define MX_SPI4_MISO_Port                      GPIOE
#define MX_SPI4_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI4_MISO_Pull                      GPIO_NOPULL
#define MX_SPI4_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI4_MISO_Alternate                 GPIO_AF5_SPI4

/* SPI4_MOSI */
#define MX_SPI4_MOSI                           PE6
#define MX_SPI4_MOSI_Pin                       GPIO_PIN_6
#define MX_SPI4_MOSI_Port                      GPIOE
#define MX_SPI4_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI4_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI4_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI4_MOSI_Alternate                 GPIO_AF5_SPI4

#endif  /* __MX_DEVICE_H */
