/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:02
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB6
#define MX_I2C1_SCL_Pin                        GPIO_PIN_6
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB7
#define MX_I2C1_SDA_Pin                        GPIO_PIN_7
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ SDIO           -----------------------------*/
#define MX_SDIO                                1

/* Pins */

/* SDIO_D2 */
#define MX_SDIO_D2                             PC10
#define MX_SDIO_D2_Pin                         GPIO_PIN_10
#define MX_SDIO_D2_Port                        GPIOC
#define MX_SDIO_D2_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D2_Pull                        GPIO_NOPULL
#define MX_SDIO_D2_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D2_Alternate                   GPIO_AF12_SDIO

/* SDIO_D3 */
#define MX_SDIO_D3                             PC11
#define MX_SDIO_D3_Pin                         GPIO_PIN_11
#define MX_SDIO_D3_Port                        GPIOC
#define MX_SDIO_D3_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D3_Pull                        GPIO_NOPULL
#define MX_SDIO_D3_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D3_Alternate                   GPIO_AF12_SDIO

/* SDIO_CK */
#define MX_SDIO_CK                             PC12
#define MX_SDIO_CK_Pin                         GPIO_PIN_12
#define MX_SDIO_CK_Port                        GPIOC
#define MX_SDIO_CK_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_CK_Pull                        GPIO_NOPULL
#define MX_SDIO_CK_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CK_Alternate                   GPIO_AF12_SDIO

/* SDIO_D0 */
#define MX_SDIO_D0                             PC8
#define MX_SDIO_D0_Pin                         GPIO_PIN_8
#define MX_SDIO_D0_Port                        GPIOC
#define MX_SDIO_D0_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D0_Pull                        GPIO_NOPULL
#define MX_SDIO_D0_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D0_Alternate                   GPIO_AF12_SDIO

/* SDIO_D1 */
#define MX_SDIO_D1                             PC9
#define MX_SDIO_D1_Pin                         GPIO_PIN_9
#define MX_SDIO_D1_Port                        GPIOC
#define MX_SDIO_D1_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D1_Pull                        GPIO_NOPULL
#define MX_SDIO_D1_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D1_Alternate                   GPIO_AF12_SDIO

/* SDIO_CMD */
#define MX_SDIO_CMD                            PD2
#define MX_SDIO_CMD_Pin                        GPIO_PIN_2
#define MX_SDIO_CMD_Port                       GPIOD
#define MX_SDIO_CMD_Mode                       GPIO_MODE_AF_PP
#define MX_SDIO_CMD_Pull                       GPIO_NOPULL
#define MX_SDIO_CMD_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CMD_Alternate                  GPIO_AF12_SDIO

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_SCK */
#define MX_SPI1_SCK                            PA5
#define MX_SPI1_SCK_Pin                        GPIO_PIN_5
#define MX_SPI1_SCK_Port                       GPIOA
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/* SPI1_MISO */
#define MX_SPI1_MISO                           PA6
#define MX_SPI1_MISO_Pin                       GPIO_PIN_6
#define MX_SPI1_MISO_Port                      GPIOA
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MISO_Alternate                 GPIO_AF5_SPI1

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PA7
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_7
#define MX_SPI1_MOSI_Port                      GPIOA
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/*------------------------------ SPI2           -----------------------------*/
#define MX_SPI2                                1

/* Pins */

/* SPI2_SCK */
#define MX_SPI2_SCK                            PB13
#define MX_SPI2_SCK_Pin                        GPIO_PIN_13
#define MX_SPI2_SCK_Port                       GPIOB
#define MX_SPI2_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI2_SCK_Pull                       GPIO_NOPULL
#define MX_SPI2_SCK_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_SCK_Alternate                  GPIO_AF5_SPI2

/* SPI2_MISO */
#define MX_SPI2_MISO                           PB14
#define MX_SPI2_MISO_Pin                       GPIO_PIN_14
#define MX_SPI2_MISO_Port                      GPIOB
#define MX_SPI2_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MISO_Pull                      GPIO_NOPULL
#define MX_SPI2_MISO_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MISO_Alternate                 GPIO_AF5_SPI2

/* SPI2_MOSI */
#define MX_SPI2_MOSI                           PB15
#define MX_SPI2_MOSI_Pin                       GPIO_PIN_15
#define MX_SPI2_MOSI_Port                      GPIOB
#define MX_SPI2_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI2_MOSI_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MOSI_Alternate                 GPIO_AF5_SPI2

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_ASYNC

/* Pins */

/* USART1_RX */
#define MX_USART1_RX                           PA10
#define MX_USART1_RX_Pin                       GPIO_PIN_10
#define MX_USART1_RX_Port                      GPIOA
#define MX_USART1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_RX_Pull                      GPIO_NOPULL
#define MX_USART1_RX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Alternate                 GPIO_AF7_USART1

/* USART1_TX */
#define MX_USART1_TX                           PA9
#define MX_USART1_TX_Pin                       GPIO_PIN_9
#define MX_USART1_TX_Port                      GPIOA
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_TX_Pull                      GPIO_NOPULL
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Alternate                 GPIO_AF7_USART1

/*------------------------------ USART2         -----------------------------*/
#define MX_USART2                              1

/* Virtual mode */
#define MX_USART2_VM                           VM_ASYNC

/* Pins */

/* USART2_TX */
#define MX_USART2_TX                           PA2
#define MX_USART2_TX_Pin                       GPIO_PIN_2
#define MX_USART2_TX_Port                      GPIOA
#define MX_USART2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_TX_Pull                      GPIO_NOPULL
#define MX_USART2_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Alternate                 GPIO_AF7_USART2

/* USART2_RX */
#define MX_USART2_RX                           PA3
#define MX_USART2_RX_Pin                       GPIO_PIN_3
#define MX_USART2_RX_Port                      GPIOA
#define MX_USART2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_RX_Pull                      GPIO_NOPULL
#define MX_USART2_RX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Alternate                 GPIO_AF7_USART2

/*------------------------------ USB            -----------------------------*/
#define MX_USB                                 1

/* Pins */

/* USB_DM */
#define MX_USB_DM                              PA11

/* USB_DP */
#define MX_USB_DP                              PA12

#endif  /* __MX_DEVICE_H */
