/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:05
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PA15
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_15
#define MX_SPI1_MOSI_Port                      GPIOA
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/* SPI1_MISO */
#define MX_SPI1_MISO                           PB3
#define MX_SPI1_MISO_Pin                       GPIO_PIN_3
#define MX_SPI1_MISO_Port                      GPIOB
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MISO_Alternate                 GPIO_AF5_SPI1

/* SPI1_SCK */
#define MX_SPI1_SCK                            PB4
#define MX_SPI1_SCK_Pin                        GPIO_PIN_4
#define MX_SPI1_SCK_Port                       GPIOB
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_ASYNC

/* Pins */

/* USART1_RX */
#define MX_USART1_RX                           PA8
#define MX_USART1_RX_Pin                       GPIO_PIN_8
#define MX_USART1_RX_Port                      GPIOA
#define MX_USART1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_RX_Pull                      GPIO_NOPULL
#define MX_USART1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Alternate                 GPIO_AF7_USART1

/* USART1_TX */
#define MX_USART1_TX                           PB12
#define MX_USART1_TX_Pin                       GPIO_PIN_12
#define MX_USART1_TX_Port                      GPIOB
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_TX_Pull                      GPIO_NOPULL
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Alternate                 GPIO_AF7_USART1

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB1
#define MX_I2C1_SDA_Pin                        GPIO_PIN_1
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB2
#define MX_I2C1_SCL_Pin                        GPIO_PIN_2
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_RX */
#define MX_LPUART1_RX                          PA1
#define MX_LPUART1_RX_Pin                      GPIO_PIN_1
#define MX_LPUART1_RX_Port                     GPIOA
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Alternate                GPIO_AF8_LPUART1

/* LPUART1_TX */
#define MX_LPUART1_TX                          PB11
#define MX_LPUART1_TX_Pin                      GPIO_PIN_11
#define MX_LPUART1_TX_Port                     GPIOB
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Alternate                GPIO_AF8_LPUART1

#endif  /* __MX_DEVICE_H */
