/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:54
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ CAN1           -----------------------------*/
#define MX_CAN1                                1

/* Pins */

/* CAN1_RX */
#define MX_CAN1_RX                             PD0
#define MX_CAN1_RX_Pin                         GPIO_PIN_0
#define MX_CAN1_RX_Port                        GPIOD
#define MX_CAN1_RX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN1_RX_Pull                        GPIO_NOPULL
#define MX_CAN1_RX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_RX_Alternate                   GPIO_AF9_CAN1

/* CAN1_TX */
#define MX_CAN1_TX                             PD1
#define MX_CAN1_TX_Pin                         GPIO_PIN_1
#define MX_CAN1_TX_Port                        GPIOD
#define MX_CAN1_TX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN1_TX_Pull                        GPIO_NOPULL
#define MX_CAN1_TX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_TX_Alternate                   GPIO_AF9_CAN1

/*------------------------------ USB_OTG_FS     -----------------------------*/
#define MX_USB_OTG_FS                          1

/* Virtual mode */
#define MX_USB_OTG_FS_VM                       Host_Only

/* Pins */

/* USB_OTG_FS_DM */
#define MX_USB_OTG_FS_DM                       PA11
#define MX_USB_OTG_FS_DM_Pin                   GPIO_PIN_11
#define MX_USB_OTG_FS_DM_Port                  GPIOA
#define MX_USB_OTG_FS_DM_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DM_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DM_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DM_Alternate             GPIO_AF10_OTG_FS

/* USB_OTG_FS_DP */
#define MX_USB_OTG_FS_DP                       PA12
#define MX_USB_OTG_FS_DP_Pin                   GPIO_PIN_12
#define MX_USB_OTG_FS_DP_Port                  GPIOA
#define MX_USB_OTG_FS_DP_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DP_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DP_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DP_Alternate             GPIO_AF10_OTG_FS

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB8
#define MX_I2C1_SCL_Pin                        GPIO_PIN_8
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB9
#define MX_I2C1_SDA_Pin                        GPIO_PIN_9
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ SDIO           -----------------------------*/
#define MX_SDIO                                1

/* Pins */

/* SDIO_D0 */
#define MX_SDIO_D0                             PB4
#define MX_SDIO_D0_Pin                         GPIO_PIN_4
#define MX_SDIO_D0_Port                        GPIOB
#define MX_SDIO_D0_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D0_Pull                        GPIO_NOPULL
#define MX_SDIO_D0_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D0_Alternate                   GPIO_AF12_SDIO

/* SDIO_D3 */
#define MX_SDIO_D3                             PB5
#define MX_SDIO_D3_Pin                         GPIO_PIN_5
#define MX_SDIO_D3_Port                        GPIOB
#define MX_SDIO_D3_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D3_Pull                        GPIO_NOPULL
#define MX_SDIO_D3_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D3_Alternate                   GPIO_AF12_SDIO

/* SDIO_D2 */
#define MX_SDIO_D2                             PC10
#define MX_SDIO_D2_Pin                         GPIO_PIN_10
#define MX_SDIO_D2_Port                        GPIOC
#define MX_SDIO_D2_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D2_Pull                        GPIO_NOPULL
#define MX_SDIO_D2_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D2_Alternate                   GPIO_AF12_SDIO

/* SDIO_CK */
#define MX_SDIO_CK                             PC12
#define MX_SDIO_CK_Pin                         GPIO_PIN_12
#define MX_SDIO_CK_Port                        GPIOC
#define MX_SDIO_CK_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_CK_Pull                        GPIO_NOPULL
#define MX_SDIO_CK_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CK_Alternate                   GPIO_AF12_SDIO

/* SDIO_D1 */
#define MX_SDIO_D1                             PC9
#define MX_SDIO_D1_Pin                         GPIO_PIN_9
#define MX_SDIO_D1_Port                        GPIOC
#define MX_SDIO_D1_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D1_Pull                        GPIO_NOPULL
#define MX_SDIO_D1_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D1_Alternate                   GPIO_AF12_SDIO

/* SDIO_CMD */
#define MX_SDIO_CMD                            PD2
#define MX_SDIO_CMD_Pin                        GPIO_PIN_2
#define MX_SDIO_CMD_Port                       GPIOD
#define MX_SDIO_CMD_Mode                       GPIO_MODE_AF_PP
#define MX_SDIO_CMD_Pull                       GPIO_NOPULL
#define MX_SDIO_CMD_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CMD_Alternate                  GPIO_AF12_SDIO

/*------------------------------ SPI2           -----------------------------*/
#define MX_SPI2                                1

/* Pins */

/* SPI2_MOSI */
#define MX_SPI2_MOSI                           PC3
#define MX_SPI2_MOSI_Pin                       GPIO_PIN_3
#define MX_SPI2_MOSI_Port                      GPIOC
#define MX_SPI2_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI2_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI2_MOSI_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MOSI_Alternate                 GPIO_AF5_SPI2

/* SPI2_SCK */
#define MX_SPI2_SCK                            PD3
#define MX_SPI2_SCK_Pin                        GPIO_PIN_3
#define MX_SPI2_SCK_Port                       GPIOD
#define MX_SPI2_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI2_SCK_Pull                       GPIO_NOPULL
#define MX_SPI2_SCK_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_SCK_Alternate                  GPIO_AF5_SPI2

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_SYNC

/* Pins */

/* USART1_TX */
#define MX_USART1_TX                           PA15
#define MX_USART1_TX_Pin                       GPIO_PIN_15
#define MX_USART1_TX_Port                      GPIOA
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_TX_Pull                      GPIO_NOPULL
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Alternate                 GPIO_AF7_USART1

/* USART1_CK */
#define MX_USART1_CK                           PA8
#define MX_USART1_CK_Pin                       GPIO_PIN_8
#define MX_USART1_CK_Port                      GPIOA
#define MX_USART1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_CK_Pull                      GPIO_NOPULL
#define MX_USART1_CK_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_CK_Alternate                 GPIO_AF7_USART1

/* USART1_RX */
#define MX_USART1_RX                           PB3
#define MX_USART1_RX_Pin                       GPIO_PIN_3
#define MX_USART1_RX_Port                      GPIOB
#define MX_USART1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_RX_Pull                      GPIO_NOPULL
#define MX_USART1_RX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Alternate                 GPIO_AF7_USART1

/*------------------------------ USART6         -----------------------------*/
#define MX_USART6                              1

/* Virtual mode */
#define MX_USART6_VM                           VM_ASYNC

/* Pins */

/* USART6_TX */
#define MX_USART6_TX                           PG14
#define MX_USART6_TX_Pin                       GPIO_PIN_14
#define MX_USART6_TX_Port                      GPIOG
#define MX_USART6_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART6_TX_Pull                      GPIO_NOPULL
#define MX_USART6_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_TX_Alternate                 GPIO_AF8_USART6

/* USART6_RX */
#define MX_USART6_RX                           PG9
#define MX_USART6_RX_Pin                       GPIO_PIN_9
#define MX_USART6_RX_Port                      GPIOG
#define MX_USART6_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART6_RX_Pull                      GPIO_NOPULL
#define MX_USART6_RX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_RX_Alternate                 GPIO_AF8_USART6

#endif  /* __MX_DEVICE_H */
