/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:04
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ FDCAN1         -----------------------------*/
#define MX_FDCAN1                              1

/* Pins */

/* FDCAN1_RX */
#define MX_FDCAN1_RX                           PD0
#define MX_FDCAN1_RX_Pin                       GPIO_PIN_0
#define MX_FDCAN1_RX_Port                      GPIOD
#define MX_FDCAN1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_RX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_RX_Alternate                 GPIO_AF9_FDCAN1

/* FDCAN1_TX */
#define MX_FDCAN1_TX                           PH13
#define MX_FDCAN1_TX_Pin                       GPIO_PIN_13
#define MX_FDCAN1_TX_Port                      GPIOH
#define MX_FDCAN1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_TX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_TX_Alternate                 GPIO_AF9_FDCAN1

/*------------------------------ SDMMC1         -----------------------------*/
#define MX_SDMMC1                              1

/* Pins */

/* SDMMC1_D2 */
#define MX_SDMMC1_D2                           PC10
#define MX_SDMMC1_D2_Pin                       GPIO_PIN_10
#define MX_SDMMC1_D2_Port                      GPIOC
#define MX_SDMMC1_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D2_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D2_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D3 */
#define MX_SDMMC1_D3                           PC11
#define MX_SDMMC1_D3_Pin                       GPIO_PIN_11
#define MX_SDMMC1_D3_Port                      GPIOC
#define MX_SDMMC1_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D3_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D3_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CK */
#define MX_SDMMC1_CK                           PC12
#define MX_SDMMC1_CK_Pin                       GPIO_PIN_12
#define MX_SDMMC1_CK_Port                      GPIOC
#define MX_SDMMC1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC1_CK_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_CK_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D0 */
#define MX_SDMMC1_D0                           PC8
#define MX_SDMMC1_D0_Pin                       GPIO_PIN_8
#define MX_SDMMC1_D0_Port                      GPIOC
#define MX_SDMMC1_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D0_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D0_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D1 */
#define MX_SDMMC1_D1                           PC9
#define MX_SDMMC1_D1_Pin                       GPIO_PIN_9
#define MX_SDMMC1_D1_Port                      GPIOC
#define MX_SDMMC1_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D1_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D1_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CMD */
#define MX_SDMMC1_CMD                          PD2
#define MX_SDMMC1_CMD_Pin                      GPIO_PIN_2
#define MX_SDMMC1_CMD_Port                     GPIOD
#define MX_SDMMC1_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC1_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC1_CMD_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_CMD_Alternate                GPIO_AF12_SDMMC1

/*------------------------------ SDMMC2         -----------------------------*/
#define MX_SDMMC2                              1

/* Pins */

/* SDMMC2_D0 */
#define MX_SDMMC2_D0                           PB14
#define MX_SDMMC2_D0_Pin                       GPIO_PIN_14
#define MX_SDMMC2_D0_Port                      GPIOB
#define MX_SDMMC2_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D0_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D0_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_D1 */
#define MX_SDMMC2_D1                           PB15
#define MX_SDMMC2_D1_Pin                       GPIO_PIN_15
#define MX_SDMMC2_D1_Port                      GPIOB
#define MX_SDMMC2_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D1_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D1_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_D2 */
#define MX_SDMMC2_D2                           PB3
#define MX_SDMMC2_D2_Pin                       GPIO_PIN_3
#define MX_SDMMC2_D2_Port                      GPIOB
#define MX_SDMMC2_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D2_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D2_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_D3 */
#define MX_SDMMC2_D3                           PB4
#define MX_SDMMC2_D3_Pin                       GPIO_PIN_4
#define MX_SDMMC2_D3_Port                      GPIOB
#define MX_SDMMC2_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D3_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_D3_Alternate                 GPIO_AF12_SDMMC2

/* SDMMC2_CK */
#define MX_SDMMC2_CK                           PD6
#define MX_SDMMC2_CK_Pin                       GPIO_PIN_6
#define MX_SDMMC2_CK_Port                      GPIOD
#define MX_SDMMC2_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC2_CK_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_CK_Alternate                 GPIO_AF11_SDMMC2

/* SDMMC2_CMD */
#define MX_SDMMC2_CMD                          PD7
#define MX_SDMMC2_CMD_Pin                      GPIO_PIN_7
#define MX_SDMMC2_CMD_Port                     GPIOD
#define MX_SDMMC2_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC2_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC2_CMD_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC2_CMD_Alternate                GPIO_AF11_SDMMC2

/*------------------------------ UART4          -----------------------------*/
#define MX_UART4                               1

/* Pins */

/* UART4_TX */
#define MX_UART4_TX                            PA0
#define MX_UART4_TX_Pin                        GPIO_PIN_0
#define MX_UART4_TX_Port                       GPIOA
#define MX_UART4_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_TX_Pull                       GPIO_NOPULL
#define MX_UART4_TX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_TX_Alternate                  GPIO_AF8_UART4

/* UART4_RX */
#define MX_UART4_RX                            PA1
#define MX_UART4_RX_Pin                        GPIO_PIN_1
#define MX_UART4_RX_Port                       GPIOA
#define MX_UART4_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_RX_Pull                       GPIO_NOPULL
#define MX_UART4_RX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_RX_Alternate                  GPIO_AF8_UART4

/*------------------------------ USART3         -----------------------------*/
#define MX_USART3                              1

/* Virtual mode */
#define MX_USART3_VM                           VM_ASYNC

/* Pins */

/* USART3_RX */
#define MX_USART3_RX                           PA5
#define MX_USART3_RX_Pin                       GPIO_PIN_5
#define MX_USART3_RX_Port                      GPIOA
#define MX_USART3_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_RX_Pull                      GPIO_NOPULL
#define MX_USART3_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART3_RX_Alternate                 GPIO_AF7_USART3

/* USART3_TX */
#define MX_USART3_TX                           PA7
#define MX_USART3_TX_Pin                       GPIO_PIN_7
#define MX_USART3_TX_Port                      GPIOA
#define MX_USART3_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_TX_Pull                      GPIO_NOPULL
#define MX_USART3_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART3_TX_Alternate                 GPIO_AF7_USART3

/*------------------------------ USB_OTG_FS     -----------------------------*/
#define MX_USB_OTG_FS                          1

/* Pins */

/* USB_OTG_FS_ID */
#define MX_USB_OTG_FS_ID                       PA10

/* USB_OTG_FS_DM */
#define MX_USB_OTG_FS_DM                       PA11

/* USB_OTG_FS_DP */
#define MX_USB_OTG_FS_DP                       PA12

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB6
#define MX_I2C1_SCL_Pin                        GPIO_PIN_6
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB9
#define MX_I2C1_SDA_Pin                        GPIO_PIN_9
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ I2C3           -----------------------------*/
#define MX_I2C3                                1

/* Pins */

/* I2C3_SCL */
#define MX_I2C3_SCL                            PH7
#define MX_I2C3_SCL_Pin                        GPIO_PIN_7
#define MX_I2C3_SCL_Port                       GPIOH
#define MX_I2C3_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SCL_Pull                       GPIO_NOPULL
#define MX_I2C3_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SCL_Alternate                  GPIO_AF4_I2C3

/* I2C3_SDA */
#define MX_I2C3_SDA                            PH8
#define MX_I2C3_SDA_Pin                        GPIO_PIN_8
#define MX_I2C3_SDA_Port                       GPIOH
#define MX_I2C3_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SDA_Pull                       GPIO_NOPULL
#define MX_I2C3_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SDA_Alternate                  GPIO_AF4_I2C3

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_TX */
#define MX_LPUART1_TX                          PG7
#define MX_LPUART1_TX_Pin                      GPIO_PIN_7
#define MX_LPUART1_TX_Port                     GPIOG
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Alternate                GPIO_AF8_LPUART1

/* LPUART1_RX */
#define MX_LPUART1_RX                          PG8
#define MX_LPUART1_RX_Pin                      GPIO_PIN_8
#define MX_LPUART1_RX_Port                     GPIOG
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Alternate                GPIO_AF8_LPUART1

#endif  /* __MX_DEVICE_H */
