/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:57
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SDMMC1         -----------------------------*/
#define MX_SDMMC1                              1

/* Pins */

/* SDMMC1_D0 */
#define MX_SDMMC1_D0                           PA10
#define MX_SDMMC1_D0_Pin                       GPIO_PIN_10
#define MX_SDMMC1_D0_Port                      GPIOA
#define MX_SDMMC1_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D0_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D0_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CKIN */
#define MX_SDMMC1_CKIN                         PB8
#define MX_SDMMC1_CKIN_Pin                     GPIO_PIN_8
#define MX_SDMMC1_CKIN_Port                    GPIOB
#define MX_SDMMC1_CKIN_Mode                    GPIO_MODE_AF_PP
#define MX_SDMMC1_CKIN_Pull                    GPIO_NOPULL
#define MX_SDMMC1_CKIN_Speed                   GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_CKIN_Alternate               GPIO_AF7_SDMMC1

/* SDMMC1_CDIR */
#define MX_SDMMC1_CDIR                         PB9
#define MX_SDMMC1_CDIR_Pin                     GPIO_PIN_9
#define MX_SDMMC1_CDIR_Port                    GPIOB
#define MX_SDMMC1_CDIR_Mode                    GPIO_MODE_AF_PP
#define MX_SDMMC1_CDIR_Pull                    GPIO_NOPULL
#define MX_SDMMC1_CDIR_Speed                   GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_CDIR_Alternate               GPIO_AF7_SDMMC1

/* SDMMC1_D2 */
#define MX_SDMMC1_D2                           PC10
#define MX_SDMMC1_D2_Pin                       GPIO_PIN_10
#define MX_SDMMC1_D2_Port                      GPIOC
#define MX_SDMMC1_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D2_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D2_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D3 */
#define MX_SDMMC1_D3                           PC11
#define MX_SDMMC1_D3_Pin                       GPIO_PIN_11
#define MX_SDMMC1_D3_Port                      GPIOC
#define MX_SDMMC1_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D3_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D3_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CK */
#define MX_SDMMC1_CK                           PC12
#define MX_SDMMC1_CK_Pin                       GPIO_PIN_12
#define MX_SDMMC1_CK_Port                      GPIOC
#define MX_SDMMC1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC1_CK_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_CK_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D0DIR */
#define MX_SDMMC1_D0DIR                        PC6
#define MX_SDMMC1_D0DIR_Pin                    GPIO_PIN_6
#define MX_SDMMC1_D0DIR_Port                   GPIOC
#define MX_SDMMC1_D0DIR_Mode                   GPIO_MODE_AF_PP
#define MX_SDMMC1_D0DIR_Pull                   GPIO_NOPULL
#define MX_SDMMC1_D0DIR_Speed                  GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D0DIR_Alternate              GPIO_AF8_SDMMC1

/* SDMMC1_D123DIR */
#define MX_SDMMC1_D123DIR                      PC7
#define MX_SDMMC1_D123DIR_Pin                  GPIO_PIN_7
#define MX_SDMMC1_D123DIR_Port                 GPIOC
#define MX_SDMMC1_D123DIR_Mode                 GPIO_MODE_AF_PP
#define MX_SDMMC1_D123DIR_Pull                 GPIO_NOPULL
#define MX_SDMMC1_D123DIR_Speed                GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D123DIR_Alternate            GPIO_AF8_SDMMC1

/* SDMMC1_D1 */
#define MX_SDMMC1_D1                           PC9
#define MX_SDMMC1_D1_Pin                       GPIO_PIN_9
#define MX_SDMMC1_D1_Port                      GPIOC
#define MX_SDMMC1_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D1_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_D1_Alternate                 GPIO_AF7_SDMMC1

/* SDMMC1_CMD */
#define MX_SDMMC1_CMD                          PD2
#define MX_SDMMC1_CMD_Pin                      GPIO_PIN_2
#define MX_SDMMC1_CMD_Port                     GPIOD
#define MX_SDMMC1_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC1_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC1_CMD_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_SDMMC1_CMD_Alternate                GPIO_AF12_SDMMC1

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_MISO */
#define MX_SPI1_MISO                           PB4_NJTRST_

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PB5
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_5
#define MX_SPI1_MOSI_Port                      GPIOB
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/* SPI1_SCK */
#define MX_SPI1_SCK                            PG11
#define MX_SPI1_SCK_Pin                        GPIO_PIN_11
#define MX_SPI1_SCK_Port                       GPIOG
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/*------------------------------ UART4          -----------------------------*/
#define MX_UART4                               1

/* Pins */

/* UART4_RX */
#define MX_UART4_RX                            PD0
#define MX_UART4_RX_Pin                        GPIO_PIN_0
#define MX_UART4_RX_Port                       GPIOD
#define MX_UART4_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_RX_Pull                       GPIO_NOPULL
#define MX_UART4_RX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_RX_Alternate                  GPIO_AF8_UART4

/* UART4_TX */
#define MX_UART4_TX                            PD1
#define MX_UART4_TX_Pin                        GPIO_PIN_1
#define MX_UART4_TX_Port                       GPIOD
#define MX_UART4_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_TX_Pull                       GPIO_NOPULL
#define MX_UART4_TX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_TX_Alternate                  GPIO_AF8_UART4

/*------------------------------ USB            -----------------------------*/
#define MX_USB                                 1

/* Virtual mode */
#define MX_USB_VM                              Device_Only

/* Pins */

/* USB_DM */
#define MX_USB_DM                              PA11
#define MX_USB_DM_Pin                          GPIO_PIN_11
#define MX_USB_DM_Port                         GPIOA
#define MX_USB_DM_Mode                         GPIO_MODE_AF_PP
#define MX_USB_DM_Pull                         GPIO_NOPULL
#define MX_USB_DM_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_USB_DM_Alternate                    GPIO_AF10_USB

/* USB_DP */
#define MX_USB_DP                              PA12
#define MX_USB_DP_Pin                          GPIO_PIN_12
#define MX_USB_DP_Port                         GPIOA
#define MX_USB_DP_Mode                         GPIO_MODE_AF_PP
#define MX_USB_DP_Pull                         GPIO_NOPULL
#define MX_USB_DP_Speed                        GPIO_SPEED_FREQ_LOW
#define MX_USB_DP_Alternate                    GPIO_AF10_USB

/*------------------------------ ETH            -----------------------------*/
#define MX_ETH                                 1

/* Pins */

/* ETH_CRS */
#define MX_ETH_CRS                             PA0
#define MX_ETH_CRS_Pin                         GPIO_PIN_0
#define MX_ETH_CRS_Port                        GPIOA
#define MX_ETH_CRS_Mode                        GPIO_MODE_AF_PP
#define MX_ETH_CRS_Pull                        GPIO_NOPULL
#define MX_ETH_CRS_Speed                       GPIO_SPEED_FREQ_HIGH
#define MX_ETH_CRS_Alternate                   GPIO_AF11_ETH

/* ETH_RX_CLK */
#define MX_ETH_RX_CLK                          PA1
#define MX_ETH_RX_CLK_Pin                      GPIO_PIN_1
#define MX_ETH_RX_CLK_Port                     GPIOA
#define MX_ETH_RX_CLK_Mode                     GPIO_MODE_AF_PP
#define MX_ETH_RX_CLK_Pull                     GPIO_NOPULL
#define MX_ETH_RX_CLK_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_ETH_RX_CLK_Alternate                GPIO_AF11_ETH

/* ETH_MDIO */
#define MX_ETH_MDIO                            PA2
#define MX_ETH_MDIO_Pin                        GPIO_PIN_2
#define MX_ETH_MDIO_Port                       GPIOA
#define MX_ETH_MDIO_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_MDIO_Pull                       GPIO_NOPULL
#define MX_ETH_MDIO_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_MDIO_Alternate                  GPIO_AF11_ETH

/* ETH_COL */
#define MX_ETH_COL                             PA3
#define MX_ETH_COL_Pin                         GPIO_PIN_3
#define MX_ETH_COL_Port                        GPIOA
#define MX_ETH_COL_Mode                        GPIO_MODE_AF_PP
#define MX_ETH_COL_Pull                        GPIO_NOPULL
#define MX_ETH_COL_Speed                       GPIO_SPEED_FREQ_HIGH
#define MX_ETH_COL_Alternate                   GPIO_AF11_ETH

/* ETH_RX_DV */
#define MX_ETH_RX_DV                           PA7
#define MX_ETH_RX_DV_Pin                       GPIO_PIN_7
#define MX_ETH_RX_DV_Port                      GPIOA
#define MX_ETH_RX_DV_Mode                      GPIO_MODE_AF_PP
#define MX_ETH_RX_DV_Pull                      GPIO_NOPULL
#define MX_ETH_RX_DV_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_ETH_RX_DV_Alternate                 GPIO_AF11_ETH

/* ETH_RXD3 */
#define MX_ETH_RXD3                            PB1
#define MX_ETH_RXD3_Pin                        GPIO_PIN_1
#define MX_ETH_RXD3_Port                       GPIOB
#define MX_ETH_RXD3_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD3_Pull                       GPIO_NOPULL
#define MX_ETH_RXD3_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_RXD3_Alternate                  GPIO_AF11_ETH

/* ETH_TX_EN */
#define MX_ETH_TX_EN                           PB11
#define MX_ETH_TX_EN_Pin                       GPIO_PIN_11
#define MX_ETH_TX_EN_Port                      GPIOB
#define MX_ETH_TX_EN_Mode                      GPIO_MODE_AF_PP
#define MX_ETH_TX_EN_Pull                      GPIO_NOPULL
#define MX_ETH_TX_EN_Speed                     GPIO_SPEED_FREQ_HIGH
#define MX_ETH_TX_EN_Alternate                 GPIO_AF11_ETH

/* ETH_TXD1 */
#define MX_ETH_TXD1                            PB15
#define MX_ETH_TXD1_Pin                        GPIO_PIN_15
#define MX_ETH_TXD1_Port                       GPIOB
#define MX_ETH_TXD1_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD1_Pull                       GPIO_NOPULL
#define MX_ETH_TXD1_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_TXD1_Alternate                  GPIO_AF11_ETH

/* ETH_MDC */
#define MX_ETH_MDC                             PC1
#define MX_ETH_MDC_Pin                         GPIO_PIN_1
#define MX_ETH_MDC_Port                        GPIOC
#define MX_ETH_MDC_Mode                        GPIO_MODE_AF_PP
#define MX_ETH_MDC_Pull                        GPIO_NOPULL
#define MX_ETH_MDC_Speed                       GPIO_SPEED_FREQ_HIGH
#define MX_ETH_MDC_Alternate                   GPIO_AF11_ETH

/* ETH_TXD2 */
#define MX_ETH_TXD2                            PC2
#define MX_ETH_TXD2_Pin                        GPIO_PIN_2
#define MX_ETH_TXD2_Port                       GPIOC
#define MX_ETH_TXD2_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD2_Pull                       GPIO_NOPULL
#define MX_ETH_TXD2_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_TXD2_Alternate                  GPIO_AF11_ETH

/* ETH_TX_CLK */
#define MX_ETH_TX_CLK                          PC3
#define MX_ETH_TX_CLK_Pin                      GPIO_PIN_3
#define MX_ETH_TX_CLK_Port                     GPIOC
#define MX_ETH_TX_CLK_Mode                     GPIO_MODE_AF_PP
#define MX_ETH_TX_CLK_Pull                     GPIO_NOPULL
#define MX_ETH_TX_CLK_Speed                    GPIO_SPEED_FREQ_HIGH
#define MX_ETH_TX_CLK_Alternate                GPIO_AF11_ETH

/* ETH_RXD0 */
#define MX_ETH_RXD0                            PC4
#define MX_ETH_RXD0_Pin                        GPIO_PIN_4
#define MX_ETH_RXD0_Port                       GPIOC
#define MX_ETH_RXD0_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD0_Pull                       GPIO_NOPULL
#define MX_ETH_RXD0_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_RXD0_Alternate                  GPIO_AF11_ETH

/* ETH_RXD1 */
#define MX_ETH_RXD1                            PC5
#define MX_ETH_RXD1_Pin                        GPIO_PIN_5
#define MX_ETH_RXD1_Port                       GPIOC
#define MX_ETH_RXD1_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD1_Pull                       GPIO_NOPULL
#define MX_ETH_RXD1_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_RXD1_Alternate                  GPIO_AF11_ETH

/* ETH_TXD3 */
#define MX_ETH_TXD3                            PE2
#define MX_ETH_TXD3_Pin                        GPIO_PIN_2
#define MX_ETH_TXD3_Port                       GPIOE
#define MX_ETH_TXD3_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD3_Pull                       GPIO_NOPULL
#define MX_ETH_TXD3_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_TXD3_Alternate                  GPIO_AF11_ETH

/* ETH_TXD0 */
#define MX_ETH_TXD0                            PG13
#define MX_ETH_TXD0_Pin                        GPIO_PIN_13
#define MX_ETH_TXD0_Port                       GPIOG
#define MX_ETH_TXD0_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD0_Pull                       GPIO_NOPULL
#define MX_ETH_TXD0_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_TXD0_Alternate                  GPIO_AF11_ETH

/* ETH_RXD2 */
#define MX_ETH_RXD2                            PH6
#define MX_ETH_RXD2_Pin                        GPIO_PIN_6
#define MX_ETH_RXD2_Port                       GPIOH
#define MX_ETH_RXD2_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD2_Pull                       GPIO_NOPULL
#define MX_ETH_RXD2_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_ETH_RXD2_Alternate                  GPIO_AF11_ETH

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB6
#define MX_I2C1_SCL_Pin                        GPIO_PIN_6
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB7
#define MX_I2C1_SDA_Pin                        GPIO_PIN_7
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ I2C4           -----------------------------*/
#define MX_I2C4                                1

/* Pins */

/* I2C4_SCL */
#define MX_I2C4_SCL                            PF5
#define MX_I2C4_SCL_Pin                        GPIO_PIN_5
#define MX_I2C4_SCL_Port                       GPIOF
#define MX_I2C4_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C4_SCL_Pull                       GPIO_NOPULL
#define MX_I2C4_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C4_SCL_Alternate                  GPIO_AF4_I2C4

/* I2C4_SDA */
#define MX_I2C4_SDA                            PG6
#define MX_I2C4_SDA_Pin                        GPIO_PIN_6
#define MX_I2C4_SDA_Port                       GPIOG
#define MX_I2C4_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C4_SDA_Pull                       GPIO_NOPULL
#define MX_I2C4_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C4_SDA_Alternate                  GPIO_AF4_I2C4

#endif  /* __MX_DEVICE_H */
