/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:03
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ CAN1           -----------------------------*/
#define MX_CAN1                                1

/* Pins */

/* CAN1_RX */
#define MX_CAN1_RX                             PD0
#define MX_CAN1_RX_Pin                         GPIO_PIN_0
#define MX_CAN1_RX_Port                        GPIOD
#define MX_CAN1_RX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN1_RX_Pull                        GPIO_NOPULL
#define MX_CAN1_RX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_RX_Alternate                   GPIO_AF9_CAN1

/* CAN1_TX */
#define MX_CAN1_TX                             PD1
#define MX_CAN1_TX_Pin                         GPIO_PIN_1
#define MX_CAN1_TX_Port                        GPIOD
#define MX_CAN1_TX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN1_TX_Pull                        GPIO_NOPULL
#define MX_CAN1_TX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_TX_Alternate                   GPIO_AF9_CAN1

/*------------------------------ CAN2           -----------------------------*/
#define MX_CAN2                                1

/* Pins */

/* CAN2_RX */
#define MX_CAN2_RX                             PB12
#define MX_CAN2_RX_Pin                         GPIO_PIN_12
#define MX_CAN2_RX_Port                        GPIOB
#define MX_CAN2_RX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN2_RX_Pull                        GPIO_NOPULL
#define MX_CAN2_RX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_RX_Alternate                   GPIO_AF10_CAN2

/* CAN2_TX */
#define MX_CAN2_TX                             PB13
#define MX_CAN2_TX_Pin                         GPIO_PIN_13
#define MX_CAN2_TX_Port                        GPIOB
#define MX_CAN2_TX_Mode                        GPIO_MODE_AF_PP
#define MX_CAN2_TX_Pull                        GPIO_NOPULL
#define MX_CAN2_TX_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_TX_Alternate                   GPIO_AF10_CAN2

/*------------------------------ UART4          -----------------------------*/
#define MX_UART4                               1

/* Pins */

/* UART4_TX */
#define MX_UART4_TX                            PA0
#define MX_UART4_TX_Pin                        GPIO_PIN_0
#define MX_UART4_TX_Port                       GPIOA
#define MX_UART4_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_TX_Pull                       GPIO_NOPULL
#define MX_UART4_TX_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_TX_Alternate                  GPIO_AF8_UART4

/* UART4_RX */
#define MX_UART4_RX                            PA1
#define MX_UART4_RX_Pin                        GPIO_PIN_1
#define MX_UART4_RX_Port                       GPIOA
#define MX_UART4_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_RX_Pull                       GPIO_NOPULL
#define MX_UART4_RX_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_RX_Alternate                  GPIO_AF8_UART4

/*------------------------------ USART2         -----------------------------*/
#define MX_USART2                              1

/* Virtual mode */
#define MX_USART2_VM                           VM_ASYNC

/* Pins */

/* USART2_TX */
#define MX_USART2_TX                           PA2
#define MX_USART2_TX_Pin                       GPIO_PIN_2
#define MX_USART2_TX_Port                      GPIOA
#define MX_USART2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_TX_Pull                      GPIO_NOPULL
#define MX_USART2_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Alternate                 GPIO_AF7_USART2

/* USART2_RX */
#define MX_USART2_RX                           PA3
#define MX_USART2_RX_Pin                       GPIO_PIN_3
#define MX_USART2_RX_Port                      GPIOA
#define MX_USART2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_RX_Pull                      GPIO_NOPULL
#define MX_USART2_RX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Alternate                 GPIO_AF7_USART2

/*------------------------------ USB_OTG_FS     -----------------------------*/
#define MX_USB_OTG_FS                          1

/* Virtual mode */
#define MX_USB_OTG_FS_VM                       Device_Only

/* Pins */

/* USB_OTG_FS_DM */
#define MX_USB_OTG_FS_DM                       PA11
#define MX_USB_OTG_FS_DM_Pin                   GPIO_PIN_11
#define MX_USB_OTG_FS_DM_Port                  GPIOA
#define MX_USB_OTG_FS_DM_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DM_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DM_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DM_Alternate             GPIO_AF10_OTG_FS

/* USB_OTG_FS_DP */
#define MX_USB_OTG_FS_DP                       PA12
#define MX_USB_OTG_FS_DP_Pin                   GPIO_PIN_12
#define MX_USB_OTG_FS_DP_Port                  GPIOA
#define MX_USB_OTG_FS_DP_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DP_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DP_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DP_Alternate             GPIO_AF10_OTG_FS

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SDA */
#define MX_I2C1_SDA                            PG13
#define MX_I2C1_SDA_Pin                        GPIO_PIN_13
#define MX_I2C1_SDA_Port                       GPIOG
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/* I2C1_SCL */
#define MX_I2C1_SCL                            PG14
#define MX_I2C1_SCL_Pin                        GPIO_PIN_14
#define MX_I2C1_SCL_Port                       GPIOG
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_RX */
#define MX_LPUART1_RX                          PC0
#define MX_LPUART1_RX_Pin                      GPIO_PIN_0
#define MX_LPUART1_RX_Port                     GPIOC
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_LPUART1_RX_Alternate                GPIO_AF8_LPUART1

/* LPUART1_TX */
#define MX_LPUART1_TX                          PC1
#define MX_LPUART1_TX_Pin                      GPIO_PIN_1
#define MX_LPUART1_TX_Port                     GPIOC
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_LPUART1_TX_Alternate                GPIO_AF8_LPUART1

/*------------------------------ SDMMC1         -----------------------------*/
#define MX_SDMMC1                              1

/* Pins */

/* SDMMC1_D2 */
#define MX_SDMMC1_D2                           PC10
#define MX_SDMMC1_D2_Pin                       GPIO_PIN_10
#define MX_SDMMC1_D2_Port                      GPIOC
#define MX_SDMMC1_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D2_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D2_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D3 */
#define MX_SDMMC1_D3                           PC11
#define MX_SDMMC1_D3_Pin                       GPIO_PIN_11
#define MX_SDMMC1_D3_Port                      GPIOC
#define MX_SDMMC1_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D3_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D3_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CK */
#define MX_SDMMC1_CK                           PC12
#define MX_SDMMC1_CK_Pin                       GPIO_PIN_12
#define MX_SDMMC1_CK_Port                      GPIOC
#define MX_SDMMC1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC1_CK_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CK_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D0 */
#define MX_SDMMC1_D0                           PC8
#define MX_SDMMC1_D0_Pin                       GPIO_PIN_8
#define MX_SDMMC1_D0_Port                      GPIOC
#define MX_SDMMC1_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D0_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D0_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D1 */
#define MX_SDMMC1_D1                           PC9
#define MX_SDMMC1_D1_Pin                       GPIO_PIN_9
#define MX_SDMMC1_D1_Port                      GPIOC
#define MX_SDMMC1_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D1_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D1_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CMD */
#define MX_SDMMC1_CMD                          PD2
#define MX_SDMMC1_CMD_Pin                      GPIO_PIN_2
#define MX_SDMMC1_CMD_Port                     GPIOD
#define MX_SDMMC1_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC1_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC1_CMD_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CMD_Alternate                GPIO_AF12_SDMMC1

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_SCK */
#define MX_SPI1_SCK                            PA5
#define MX_SPI1_SCK_Pin                        GPIO_PIN_5
#define MX_SPI1_SCK_Port                       GPIOA
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/* SPI1_MISO */
#define MX_SPI1_MISO                           PA6
#define MX_SPI1_MISO_Pin                       GPIO_PIN_6
#define MX_SPI1_MISO_Port                      GPIOA
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MISO_Alternate                 GPIO_AF5_SPI1

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PA7
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_7
#define MX_SPI1_MOSI_Port                      GPIOA
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/*------------------------------ SPI3           -----------------------------*/
#define MX_SPI3                                1

/* Pins */

/* SPI3_MISO */
#define MX_SPI3_MISO                           PG10
#define MX_SPI3_MISO_Pin                       GPIO_PIN_10
#define MX_SPI3_MISO_Port                      GPIOG
#define MX_SPI3_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI3_MISO_Pull                      GPIO_NOPULL
#define MX_SPI3_MISO_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_MISO_Alternate                 GPIO_AF6_SPI3

/* SPI3_MOSI */
#define MX_SPI3_MOSI                           PG11
#define MX_SPI3_MOSI_Pin                       GPIO_PIN_11
#define MX_SPI3_MOSI_Port                      GPIOG
#define MX_SPI3_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI3_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI3_MOSI_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_MOSI_Alternate                 GPIO_AF6_SPI3

/* SPI3_SCK */
#define MX_SPI3_SCK                            PG9
#define MX_SPI3_SCK_Pin                        GPIO_PIN_9
#define MX_SPI3_SCK_Port                       GPIOG
#define MX_SPI3_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI3_SCK_Pull                       GPIO_NOPULL
#define MX_SPI3_SCK_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_SCK_Alternate                  GPIO_AF6_SPI3

#endif  /* __MX_DEVICE_H */
