/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:01
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ ETH            -----------------------------*/
#define MX_ETH                                 1

/* Pins */

/* ETH_REF_CLK */
#define MX_ETH_REF_CLK                         PA1
#define MX_ETH_REF_CLK_Pin                     GPIO_PIN_1
#define MX_ETH_REF_CLK_Port                    GPIOA
#define MX_ETH_REF_CLK_Mode                    GPIO_MODE_AF_PP
#define MX_ETH_REF_CLK_Pull                    GPIO_NOPULL
#define MX_ETH_REF_CLK_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_ETH_REF_CLK_Alternate               GPIO_AF11_ETH

/* ETH_MDIO */
#define MX_ETH_MDIO                            PA2
#define MX_ETH_MDIO_Pin                        GPIO_PIN_2
#define MX_ETH_MDIO_Port                       GPIOA
#define MX_ETH_MDIO_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_MDIO_Pull                       GPIO_NOPULL
#define MX_ETH_MDIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDIO_Alternate                  GPIO_AF11_ETH

/* ETH_CRS_DV */
#define MX_ETH_CRS_DV                          PA7
#define MX_ETH_CRS_DV_Pin                      GPIO_PIN_7
#define MX_ETH_CRS_DV_Port                     GPIOA
#define MX_ETH_CRS_DV_Mode                     GPIO_MODE_AF_PP
#define MX_ETH_CRS_DV_Pull                     GPIO_NOPULL
#define MX_ETH_CRS_DV_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_ETH_CRS_DV_Alternate                GPIO_AF11_ETH

/* ETH_TX_EN */
#define MX_ETH_TX_EN                           PB11
#define MX_ETH_TX_EN_Pin                       GPIO_PIN_11
#define MX_ETH_TX_EN_Port                      GPIOB
#define MX_ETH_TX_EN_Mode                      GPIO_MODE_AF_PP
#define MX_ETH_TX_EN_Pull                      GPIO_NOPULL
#define MX_ETH_TX_EN_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_ETH_TX_EN_Alternate                 GPIO_AF11_ETH

/* ETH_TXD0 */
#define MX_ETH_TXD0                            PB12
#define MX_ETH_TXD0_Pin                        GPIO_PIN_12
#define MX_ETH_TXD0_Port                       GPIOB
#define MX_ETH_TXD0_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD0_Pull                       GPIO_NOPULL
#define MX_ETH_TXD0_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD0_Alternate                  GPIO_AF11_ETH

/* ETH_TXD1 */
#define MX_ETH_TXD1                            PB13
#define MX_ETH_TXD1_Pin                        GPIO_PIN_13
#define MX_ETH_TXD1_Port                       GPIOB
#define MX_ETH_TXD1_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD1_Pull                       GPIO_NOPULL
#define MX_ETH_TXD1_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD1_Alternate                  GPIO_AF11_ETH

/* ETH_MDC */
#define MX_ETH_MDC                             PC1
#define MX_ETH_MDC_Pin                         GPIO_PIN_1
#define MX_ETH_MDC_Port                        GPIOC
#define MX_ETH_MDC_Mode                        GPIO_MODE_AF_PP
#define MX_ETH_MDC_Pull                        GPIO_NOPULL
#define MX_ETH_MDC_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDC_Alternate                   GPIO_AF11_ETH

/* ETH_RXD0 */
#define MX_ETH_RXD0                            PC4
#define MX_ETH_RXD0_Pin                        GPIO_PIN_4
#define MX_ETH_RXD0_Port                       GPIOC
#define MX_ETH_RXD0_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD0_Pull                       GPIO_NOPULL
#define MX_ETH_RXD0_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD0_Alternate                  GPIO_AF11_ETH

/* ETH_RXD1 */
#define MX_ETH_RXD1                            PC5
#define MX_ETH_RXD1_Pin                        GPIO_PIN_5
#define MX_ETH_RXD1_Port                       GPIOC
#define MX_ETH_RXD1_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD1_Pull                       GPIO_NOPULL
#define MX_ETH_RXD1_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD1_Alternate                  GPIO_AF11_ETH

/*------------------------------ UART5          -----------------------------*/
#define MX_UART5                               1

/* Pins */

/* UART5_RX */
#define MX_UART5_RX                            PB5
#define MX_UART5_RX_Pin                        GPIO_PIN_5
#define MX_UART5_RX_Port                       GPIOB
#define MX_UART5_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART5_RX_Pull                       GPIO_NOPULL
#define MX_UART5_RX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART5_RX_Alternate                  GPIO_AF14_UART5

/* UART5_TX */
#define MX_UART5_TX                            PB6
#define MX_UART5_TX_Pin                        GPIO_PIN_6
#define MX_UART5_TX_Port                       GPIOB
#define MX_UART5_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART5_TX_Pull                       GPIO_NOPULL
#define MX_UART5_TX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART5_TX_Alternate                  GPIO_AF14_UART5

/*------------------------------ UART8          -----------------------------*/
#define MX_UART8                               1

/* Pins */

/* UART8_RX */
#define MX_UART8_RX                            PE0
#define MX_UART8_RX_Pin                        GPIO_PIN_0
#define MX_UART8_RX_Port                       GPIOE
#define MX_UART8_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART8_RX_Pull                       GPIO_NOPULL
#define MX_UART8_RX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART8_RX_Alternate                  GPIO_AF8_UART8

/* UART8_TX */
#define MX_UART8_TX                            PE1
#define MX_UART8_TX_Pin                        GPIO_PIN_1
#define MX_UART8_TX_Port                       GPIOE
#define MX_UART8_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART8_TX_Pull                       GPIO_NOPULL
#define MX_UART8_TX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART8_TX_Alternate                  GPIO_AF8_UART8

/*------------------------------ USART10        -----------------------------*/
#define MX_USART10                             1

/* Virtual mode */
#define MX_USART10_VM                          VM_ASYNC

/* Pins */

/* USART10_RX */
#define MX_USART10_RX                          PE2
#define MX_USART10_RX_Pin                      GPIO_PIN_2
#define MX_USART10_RX_Port                     GPIOE
#define MX_USART10_RX_Mode                     GPIO_MODE_AF_PP
#define MX_USART10_RX_Pull                     GPIO_NOPULL
#define MX_USART10_RX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_USART10_RX_Alternate                GPIO_AF4_USART10

/* USART10_TX */
#define MX_USART10_TX                          PE3
#define MX_USART10_TX_Pin                      GPIO_PIN_3
#define MX_USART10_TX_Port                     GPIOE
#define MX_USART10_TX_Mode                     GPIO_MODE_AF_PP
#define MX_USART10_TX_Pull                     GPIO_NOPULL
#define MX_USART10_TX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_USART10_TX_Alternate                GPIO_AF11_USART10

/*------------------------------ USB_OTG_HS     -----------------------------*/
#define MX_USB_OTG_HS                          1

/* Pins */

/* USB_OTG_HS_ID */
#define MX_USB_OTG_HS_ID                       PA10

/* USB_OTG_HS_DM */
#define MX_USB_OTG_HS_DM                       PA11

/* USB_OTG_HS_DP */
#define MX_USB_OTG_HS_DP                       PA12

/*------------------------------ FDCAN1         -----------------------------*/
#define MX_FDCAN1                              1

/* Pins */

/* FDCAN1_RX */
#define MX_FDCAN1_RX                           PD0
#define MX_FDCAN1_RX_Pin                       GPIO_PIN_0
#define MX_FDCAN1_RX_Port                      GPIOD
#define MX_FDCAN1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_RX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_RX_Alternate                 GPIO_AF9_FDCAN1

/* FDCAN1_TX */
#define MX_FDCAN1_TX                           PD1
#define MX_FDCAN1_TX_Pin                       GPIO_PIN_1
#define MX_FDCAN1_TX_Port                      GPIOD
#define MX_FDCAN1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_TX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_TX_Alternate                 GPIO_AF9_FDCAN1

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_TX */
#define MX_LPUART1_TX                          PA9
#define MX_LPUART1_TX_Pin                      GPIO_PIN_9
#define MX_LPUART1_TX_Port                     GPIOA
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Alternate                GPIO_AF3_LPUART

/* LPUART1_RX */
#define MX_LPUART1_RX                          PB7
#define MX_LPUART1_RX_Pin                      GPIO_PIN_7
#define MX_LPUART1_RX_Port                     GPIOB
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Alternate                GPIO_AF8_LPUART

/*------------------------------ SDMMC1         -----------------------------*/
#define MX_SDMMC1                              1

/* Pins */

/* SDMMC1_CKIN */
#define MX_SDMMC1_CKIN                         PB8
#define MX_SDMMC1_CKIN_Pin                     GPIO_PIN_8
#define MX_SDMMC1_CKIN_Port                    GPIOB
#define MX_SDMMC1_CKIN_Mode                    GPIO_MODE_AF_PP
#define MX_SDMMC1_CKIN_Pull                    GPIO_NOPULL
#define MX_SDMMC1_CKIN_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CKIN_Alternate               GPIO_AF12_SDMMC1

/* SDMMC1_CDIR */
#define MX_SDMMC1_CDIR                         PB9
#define MX_SDMMC1_CDIR_Pin                     GPIO_PIN_9
#define MX_SDMMC1_CDIR_Port                    GPIOB
#define MX_SDMMC1_CDIR_Mode                    GPIO_MODE_AF_PP
#define MX_SDMMC1_CDIR_Pull                    GPIO_NOPULL
#define MX_SDMMC1_CDIR_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CDIR_Alternate               GPIO_AF12_SDMMC1

/* SDMMC1_D2 */
#define MX_SDMMC1_D2                           PC10
#define MX_SDMMC1_D2_Pin                       GPIO_PIN_10
#define MX_SDMMC1_D2_Port                      GPIOC
#define MX_SDMMC1_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D2_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D2_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D3 */
#define MX_SDMMC1_D3                           PC11
#define MX_SDMMC1_D3_Pin                       GPIO_PIN_11
#define MX_SDMMC1_D3_Port                      GPIOC
#define MX_SDMMC1_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D3_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D3_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CK */
#define MX_SDMMC1_CK                           PC12
#define MX_SDMMC1_CK_Pin                       GPIO_PIN_12
#define MX_SDMMC1_CK_Port                      GPIOC
#define MX_SDMMC1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC1_CK_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CK_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D0DIR */
#define MX_SDMMC1_D0DIR                        PC6
#define MX_SDMMC1_D0DIR_Pin                    GPIO_PIN_6
#define MX_SDMMC1_D0DIR_Port                   GPIOC
#define MX_SDMMC1_D0DIR_Mode                   GPIO_MODE_AF_PP
#define MX_SDMMC1_D0DIR_Pull                   GPIO_NOPULL
#define MX_SDMMC1_D0DIR_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D0DIR_Alternate              GPIO_AF8_SDMMC1

/* SDMMC1_D123DIR */
#define MX_SDMMC1_D123DIR                      PC7
#define MX_SDMMC1_D123DIR_Pin                  GPIO_PIN_7
#define MX_SDMMC1_D123DIR_Port                 GPIOC
#define MX_SDMMC1_D123DIR_Mode                 GPIO_MODE_AF_PP
#define MX_SDMMC1_D123DIR_Pull                 GPIO_NOPULL
#define MX_SDMMC1_D123DIR_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D123DIR_Alternate            GPIO_AF8_SDMMC1

/* SDMMC1_D0 */
#define MX_SDMMC1_D0                           PC8
#define MX_SDMMC1_D0_Pin                       GPIO_PIN_8
#define MX_SDMMC1_D0_Port                      GPIOC
#define MX_SDMMC1_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D0_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D0_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_D1 */
#define MX_SDMMC1_D1                           PC9
#define MX_SDMMC1_D1_Pin                       GPIO_PIN_9
#define MX_SDMMC1_D1_Port                      GPIOC
#define MX_SDMMC1_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D1_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D1_Alternate                 GPIO_AF12_SDMMC1

/* SDMMC1_CMD */
#define MX_SDMMC1_CMD                          PD2
#define MX_SDMMC1_CMD_Pin                      GPIO_PIN_2
#define MX_SDMMC1_CMD_Port                     GPIOD
#define MX_SDMMC1_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC1_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC1_CMD_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CMD_Alternate                GPIO_AF12_SDMMC1

/*------------------------------ SDMMC2         -----------------------------*/
#define MX_SDMMC2                              1

/* Pins */

/* SDMMC2_CMD */
#define MX_SDMMC2_CMD                          PA0
#define MX_SDMMC2_CMD_Pin                      GPIO_PIN_0
#define MX_SDMMC2_CMD_Port                     GPIOA
#define MX_SDMMC2_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC2_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC2_CMD_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_CMD_Alternate                GPIO_AF9_SDMMC2

/* SDMMC2_D0 */
#define MX_SDMMC2_D0                           PB14
#define MX_SDMMC2_D0_Pin                       GPIO_PIN_14
#define MX_SDMMC2_D0_Port                      GPIOB
#define MX_SDMMC2_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D0_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D0_Alternate                 GPIO_AF9_SDMMC2

/* SDMMC2_D1 */
#define MX_SDMMC2_D1                           PB15
#define MX_SDMMC2_D1_Pin                       GPIO_PIN_15
#define MX_SDMMC2_D1_Port                      GPIOB
#define MX_SDMMC2_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D1_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D1_Alternate                 GPIO_AF9_SDMMC2

/* SDMMC2_CK */
#define MX_SDMMC2_CK                           PD6
#define MX_SDMMC2_CK_Pin                       GPIO_PIN_6
#define MX_SDMMC2_CK_Port                      GPIOD
#define MX_SDMMC2_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC2_CK_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_CK_Alternate                 GPIO_AF11_SDMMC2

/* SDMMC2_D2 */
#define MX_SDMMC2_D2                           PG11
#define MX_SDMMC2_D2_Pin                       GPIO_PIN_11
#define MX_SDMMC2_D2_Port                      GPIOG
#define MX_SDMMC2_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D2_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D2_Alternate                 GPIO_AF10_SDMMC2

/* SDMMC2_D3 */
#define MX_SDMMC2_D3                           PG12
#define MX_SDMMC2_D3_Pin                       GPIO_PIN_12
#define MX_SDMMC2_D3_Port                      GPIOG
#define MX_SDMMC2_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC2_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC2_D3_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC2_D3_Alternate                 GPIO_AF10_SDMMC2

/*------------------------------ SPI3           -----------------------------*/
#define MX_SPI3                                1

/* Pins */

/* SPI3_MOSI */
#define MX_SPI3_MOSI                           PB2
#define MX_SPI3_MOSI_Pin                       GPIO_PIN_2
#define MX_SPI3_MOSI_Port                      GPIOB
#define MX_SPI3_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI3_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI3_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI3_MOSI_Alternate                 GPIO_AF7_SPI3

/* SPI3_SCK */
#define MX_SPI3_SCK                            PB3_JTDO_TRACESWO_

/* SPI3_MISO */
#define MX_SPI3_MISO                           PB4_NJTRST_

/*------------------------------ SPI6           -----------------------------*/
#define MX_SPI6                                1

/* Pins */

/* SPI6_SCK */
#define MX_SPI6_SCK                            PA5
#define MX_SPI6_SCK_Pin                        GPIO_PIN_5
#define MX_SPI6_SCK_Port                       GPIOA
#define MX_SPI6_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI6_SCK_Pull                       GPIO_NOPULL
#define MX_SPI6_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI6_SCK_Alternate                  GPIO_AF8_SPI6

/* SPI6_MISO */
#define MX_SPI6_MISO                           PA6
#define MX_SPI6_MISO_Pin                       GPIO_PIN_6
#define MX_SPI6_MISO_Port                      GPIOA
#define MX_SPI6_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI6_MISO_Pull                      GPIO_NOPULL
#define MX_SPI6_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI6_MISO_Alternate                 GPIO_AF8_SPI6

/* SPI6_MOSI */
#define MX_SPI6_MOSI                           PG14
#define MX_SPI6_MOSI_Pin                       GPIO_PIN_14
#define MX_SPI6_MOSI_Port                      GPIOG
#define MX_SPI6_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI6_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI6_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI6_MOSI_Alternate                 GPIO_AF5_SPI6

#endif  /* __MX_DEVICE_H */
