/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:54
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SDA */
#define MX_I2C1_SDA                            PA10
#define MX_I2C1_SDA_Pin                        GPIO_PIN_10
#define MX_I2C1_SDA_Port                       GPIOA
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_NOPULL
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF6_I2C1

/* I2C1_SCL */
#define MX_I2C1_SCL                            PA9
#define MX_I2C1_SCL_Pin                        GPIO_PIN_9
#define MX_I2C1_SCL_Port                       GPIOA
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SCL_Alternate                  GPIO_AF6_I2C1

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_SCK */
#define MX_SPI1_SCK                            PA1
#define MX_SPI1_SCK_Pin                        GPIO_PIN_1
#define MX_SPI1_SCK_Port                       GPIOA
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Alternate                  GPIO_AF0_SPI1

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PA2
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_2
#define MX_SPI1_MOSI_Port                      GPIOA
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Alternate                 GPIO_AF0_SPI1

/*------------------------------ USART1         -----------------------------*/
#define MX_USART1                              1

/* Virtual mode */
#define MX_USART1_VM                           VM_SYNC

/* Pins */

/* USART1_CK */
#define MX_USART1_CK                           PA12
#define MX_USART1_CK_Pin                       GPIO_PIN_12
#define MX_USART1_CK_Port                      GPIOA
#define MX_USART1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_CK_Pull                      GPIO_NOPULL
#define MX_USART1_CK_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_CK_Alternate                 GPIO_AF1_USART1

/* USART1_TX */
#define MX_USART1_TX                           PC4
#define MX_USART1_TX_Pin                       GPIO_PIN_4
#define MX_USART1_TX_Port                      GPIOC
#define MX_USART1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_TX_Pull                      GPIO_NOPULL
#define MX_USART1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Alternate                 GPIO_AF1_USART1

/* USART1_RX */
#define MX_USART1_RX                           PC5
#define MX_USART1_RX_Pin                       GPIO_PIN_5
#define MX_USART1_RX_Port                      GPIOC
#define MX_USART1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART1_RX_Pull                      GPIO_NOPULL
#define MX_USART1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Alternate                 GPIO_AF1_USART1

/*------------------------------ USART2         -----------------------------*/
#define MX_USART2                              1

/* Virtual mode */
#define MX_USART2_VM                           VM_IRDA

/* Pins */

/* USART2_TX */
#define MX_USART2_TX                           PA14
#define MX_USART2_TX_Pin                       GPIO_PIN_14
#define MX_USART2_TX_Port                      GPIOA
#define MX_USART2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_TX_Pull                      GPIO_NOPULL
#define MX_USART2_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Alternate                 GPIO_AF1_USART2

/* USART2_RX */
#define MX_USART2_RX                           PA3
#define MX_USART2_RX_Pin                       GPIO_PIN_3
#define MX_USART2_RX_Port                      GPIOA
#define MX_USART2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_RX_Pull                      GPIO_NOPULL
#define MX_USART2_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Alternate                 GPIO_AF1_USART2

#endif  /* __MX_DEVICE_H */
