/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:53
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SDIO           -----------------------------*/
#define MX_SDIO                                1

/* Pins */

/* SDIO_D2 */
#define MX_SDIO_D2                             PC10
#define MX_SDIO_D2_Pin                         GPIO_PIN_10
#define MX_SDIO_D2_Port                        GPIOC
#define MX_SDIO_D2_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D2_Pull                        GPIO_NOPULL
#define MX_SDIO_D2_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D2_Alternate                   GPIO_AF12_SDIO

/* SDIO_D3 */
#define MX_SDIO_D3                             PC11
#define MX_SDIO_D3_Pin                         GPIO_PIN_11
#define MX_SDIO_D3_Port                        GPIOC
#define MX_SDIO_D3_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D3_Pull                        GPIO_NOPULL
#define MX_SDIO_D3_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D3_Alternate                   GPIO_AF12_SDIO

/* SDIO_CK */
#define MX_SDIO_CK                             PC12
#define MX_SDIO_CK_Pin                         GPIO_PIN_12
#define MX_SDIO_CK_Port                        GPIOC
#define MX_SDIO_CK_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_CK_Pull                        GPIO_NOPULL
#define MX_SDIO_CK_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CK_Alternate                   GPIO_AF12_SDIO

/* SDIO_D0 */
#define MX_SDIO_D0                             PC8
#define MX_SDIO_D0_Pin                         GPIO_PIN_8
#define MX_SDIO_D0_Port                        GPIOC
#define MX_SDIO_D0_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D0_Pull                        GPIO_NOPULL
#define MX_SDIO_D0_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D0_Alternate                   GPIO_AF12_SDIO

/* SDIO_D1 */
#define MX_SDIO_D1                             PC9
#define MX_SDIO_D1_Pin                         GPIO_PIN_9
#define MX_SDIO_D1_Port                        GPIOC
#define MX_SDIO_D1_Mode                        GPIO_MODE_AF_PP
#define MX_SDIO_D1_Pull                        GPIO_NOPULL
#define MX_SDIO_D1_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D1_Alternate                   GPIO_AF12_SDIO

/* SDIO_CMD */
#define MX_SDIO_CMD                            PD2
#define MX_SDIO_CMD_Pin                        GPIO_PIN_2
#define MX_SDIO_CMD_Port                       GPIOD
#define MX_SDIO_CMD_Mode                       GPIO_MODE_AF_PP
#define MX_SDIO_CMD_Pull                       GPIO_NOPULL
#define MX_SDIO_CMD_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CMD_Alternate                  GPIO_AF12_SDIO

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_MISO */
#define MX_SPI1_MISO                           PA6
#define MX_SPI1_MISO_Pin                       GPIO_PIN_6
#define MX_SPI1_MISO_Port                      GPIOA
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MISO_Alternate                 GPIO_AF5_SPI1

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PA7
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_7
#define MX_SPI1_MOSI_Port                      GPIOA
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/* SPI1_SCK */
#define MX_SPI1_SCK                            PB3
#define MX_SPI1_SCK_Pin                        GPIO_PIN_3
#define MX_SPI1_SCK_Port                       GPIOB
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/*------------------------------ UART4          -----------------------------*/
#define MX_UART4                               1

/* Virtual mode */
#define MX_UART4_VM                            Asynchronous

/* Pins */

/* UART4_TX */
#define MX_UART4_TX                            PA0
#define MX_UART4_TX_Pin                        GPIO_PIN_0
#define MX_UART4_TX_Port                       GPIOA
#define MX_UART4_TX_Mode                       GPIO_MODE_AF_OD
#define MX_UART4_TX_Pull                       GPIO_PULLUP
#define MX_UART4_TX_Speed                      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_TX_Alternate                  GPIO_AF8_UART4

/*------------------------------ USART3         -----------------------------*/
#define MX_USART3                              1

/* Virtual mode */
#define MX_USART3_VM                           VM_ASYNC

/* Pins */

/* USART3_TX */
#define MX_USART3_TX                           PD8
#define MX_USART3_TX_Pin                       GPIO_PIN_8
#define MX_USART3_TX_Port                      GPIOD
#define MX_USART3_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_TX_Pull                      GPIO_NOPULL
#define MX_USART3_TX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_TX_Alternate                 GPIO_AF7_USART3

/* USART3_RX */
#define MX_USART3_RX                           PD9
#define MX_USART3_RX_Pin                       GPIO_PIN_9
#define MX_USART3_RX_Port                      GPIOD
#define MX_USART3_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_RX_Pull                      GPIO_NOPULL
#define MX_USART3_RX_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_RX_Alternate                 GPIO_AF7_USART3

/*------------------------------ USB_OTG_FS     -----------------------------*/
#define MX_USB_OTG_FS                          1

/* Virtual mode */
#define MX_USB_OTG_FS_VM                       Host_Only

/* Pins */

/* USB_OTG_FS_DM */
#define MX_USB_OTG_FS_DM                       PA11
#define MX_USB_OTG_FS_DM_Pin                   GPIO_PIN_11
#define MX_USB_OTG_FS_DM_Port                  GPIOA
#define MX_USB_OTG_FS_DM_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DM_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DM_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DM_Alternate             GPIO_AF10_OTG_FS

/* USB_OTG_FS_DP */
#define MX_USB_OTG_FS_DP                       PA12
#define MX_USB_OTG_FS_DP_Pin                   GPIO_PIN_12
#define MX_USB_OTG_FS_DP_Port                  GPIOA
#define MX_USB_OTG_FS_DP_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DP_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DP_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DP_Alternate             GPIO_AF10_OTG_FS

/*------------------------------ USB_OTG_HS     -----------------------------*/
#define MX_USB_OTG_HS                          1

/* Virtual mode */
#define MX_USB_OTG_HS_VM                       Device_HS

/* Pins */

/* USB_OTG_HS_ULPI_D0 */
#define MX_USB_OTG_HS_ULPI_D0                  PA3
#define MX_USB_OTG_HS_ULPI_D0_Pin              GPIO_PIN_3
#define MX_USB_OTG_HS_ULPI_D0_Port             GPIOA
#define MX_USB_OTG_HS_ULPI_D0_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D0_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D0_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D0_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_CK */
#define MX_USB_OTG_HS_ULPI_CK                  PA5
#define MX_USB_OTG_HS_ULPI_CK_Pin              GPIO_PIN_5
#define MX_USB_OTG_HS_ULPI_CK_Port             GPIOA
#define MX_USB_OTG_HS_ULPI_CK_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_CK_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_CK_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_CK_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_D1 */
#define MX_USB_OTG_HS_ULPI_D1                  PB0
#define MX_USB_OTG_HS_ULPI_D1_Pin              GPIO_PIN_0
#define MX_USB_OTG_HS_ULPI_D1_Port             GPIOB
#define MX_USB_OTG_HS_ULPI_D1_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D1_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D1_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D1_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_D2 */
#define MX_USB_OTG_HS_ULPI_D2                  PB1
#define MX_USB_OTG_HS_ULPI_D2_Pin              GPIO_PIN_1
#define MX_USB_OTG_HS_ULPI_D2_Port             GPIOB
#define MX_USB_OTG_HS_ULPI_D2_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D2_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D2_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D2_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_D3 */
#define MX_USB_OTG_HS_ULPI_D3                  PB10
#define MX_USB_OTG_HS_ULPI_D3_Pin              GPIO_PIN_10
#define MX_USB_OTG_HS_ULPI_D3_Port             GPIOB
#define MX_USB_OTG_HS_ULPI_D3_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D3_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D3_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D3_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_D4 */
#define MX_USB_OTG_HS_ULPI_D4                  PB11
#define MX_USB_OTG_HS_ULPI_D4_Pin              GPIO_PIN_11
#define MX_USB_OTG_HS_ULPI_D4_Port             GPIOB
#define MX_USB_OTG_HS_ULPI_D4_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D4_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D4_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D4_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_D5 */
#define MX_USB_OTG_HS_ULPI_D5                  PB12
#define MX_USB_OTG_HS_ULPI_D5_Pin              GPIO_PIN_12
#define MX_USB_OTG_HS_ULPI_D5_Port             GPIOB
#define MX_USB_OTG_HS_ULPI_D5_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D5_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D5_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D5_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_D6 */
#define MX_USB_OTG_HS_ULPI_D6                  PB13
#define MX_USB_OTG_HS_ULPI_D6_Pin              GPIO_PIN_13
#define MX_USB_OTG_HS_ULPI_D6_Port             GPIOB
#define MX_USB_OTG_HS_ULPI_D6_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D6_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D6_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D6_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_D7 */
#define MX_USB_OTG_HS_ULPI_D7                  PB5
#define MX_USB_OTG_HS_ULPI_D7_Pin              GPIO_PIN_5
#define MX_USB_OTG_HS_ULPI_D7_Port             GPIOB
#define MX_USB_OTG_HS_ULPI_D7_Mode             GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_D7_Pull             GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_D7_Speed            GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_D7_Alternate        GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_STP */
#define MX_USB_OTG_HS_ULPI_STP                 PC0
#define MX_USB_OTG_HS_ULPI_STP_Pin             GPIO_PIN_0
#define MX_USB_OTG_HS_ULPI_STP_Port            GPIOC
#define MX_USB_OTG_HS_ULPI_STP_Mode            GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_STP_Pull            GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_STP_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_STP_Alternate       GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_DIR */
#define MX_USB_OTG_HS_ULPI_DIR                 PC2
#define MX_USB_OTG_HS_ULPI_DIR_Pin             GPIO_PIN_2
#define MX_USB_OTG_HS_ULPI_DIR_Port            GPIOC
#define MX_USB_OTG_HS_ULPI_DIR_Mode            GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_DIR_Pull            GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_DIR_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_DIR_Alternate       GPIO_AF10_OTG_HS

/* USB_OTG_HS_ULPI_NXT */
#define MX_USB_OTG_HS_ULPI_NXT                 PC3
#define MX_USB_OTG_HS_ULPI_NXT_Pin             GPIO_PIN_3
#define MX_USB_OTG_HS_ULPI_NXT_Port            GPIOC
#define MX_USB_OTG_HS_ULPI_NXT_Mode            GPIO_MODE_AF_PP
#define MX_USB_OTG_HS_ULPI_NXT_Pull            GPIO_NOPULL
#define MX_USB_OTG_HS_ULPI_NXT_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_HS_ULPI_NXT_Alternate       GPIO_AF10_OTG_HS

#endif  /* __MX_DEVICE_H */
