/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:44:59
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SDMMC1         -----------------------------*/
#define MX_SDMMC1                              1

/* Pins */

/* SDMMC1_D2 */
#define MX_SDMMC1_D2                           PC10
#define MX_SDMMC1_D2_Pin                       GPIO_PIN_10
#define MX_SDMMC1_D2_Port                      GPIOC
#define MX_SDMMC1_D2_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D2_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D2_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D2_Alternate                 GPIO_AF12_SDIO1

/* SDMMC1_D3 */
#define MX_SDMMC1_D3                           PC11
#define MX_SDMMC1_D3_Pin                       GPIO_PIN_11
#define MX_SDMMC1_D3_Port                      GPIOC
#define MX_SDMMC1_D3_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D3_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D3_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D3_Alternate                 GPIO_AF12_SDIO1

/* SDMMC1_CK */
#define MX_SDMMC1_CK                           PC12
#define MX_SDMMC1_CK_Pin                       GPIO_PIN_12
#define MX_SDMMC1_CK_Port                      GPIOC
#define MX_SDMMC1_CK_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_CK_Pull                      GPIO_NOPULL
#define MX_SDMMC1_CK_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CK_Alternate                 GPIO_AF12_SDIO1

/* SDMMC1_D0 */
#define MX_SDMMC1_D0                           PC8
#define MX_SDMMC1_D0_Pin                       GPIO_PIN_8
#define MX_SDMMC1_D0_Port                      GPIOC
#define MX_SDMMC1_D0_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D0_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D0_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D0_Alternate                 GPIO_AF12_SDIO1

/* SDMMC1_D1 */
#define MX_SDMMC1_D1                           PC9
#define MX_SDMMC1_D1_Pin                       GPIO_PIN_9
#define MX_SDMMC1_D1_Port                      GPIOC
#define MX_SDMMC1_D1_Mode                      GPIO_MODE_AF_PP
#define MX_SDMMC1_D1_Pull                      GPIO_NOPULL
#define MX_SDMMC1_D1_Speed                     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D1_Alternate                 GPIO_AF12_SDIO1

/* SDMMC1_CMD */
#define MX_SDMMC1_CMD                          PD2
#define MX_SDMMC1_CMD_Pin                      GPIO_PIN_2
#define MX_SDMMC1_CMD_Port                     GPIOD
#define MX_SDMMC1_CMD_Mode                     GPIO_MODE_AF_PP
#define MX_SDMMC1_CMD_Pull                     GPIO_NOPULL
#define MX_SDMMC1_CMD_Speed                    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CMD_Alternate                GPIO_AF12_SDIO1

/*------------------------------ SPI1           -----------------------------*/
#define MX_SPI1                                1

/* Pins */

/* SPI1_SCK */
#define MX_SPI1_SCK                            PA5
#define MX_SPI1_SCK_Pin                        GPIO_PIN_5
#define MX_SPI1_SCK_Port                       GPIOA
#define MX_SPI1_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI1_SCK_Pull                       GPIO_NOPULL
#define MX_SPI1_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Alternate                  GPIO_AF5_SPI1

/* SPI1_MOSI */
#define MX_SPI1_MOSI                           PD7
#define MX_SPI1_MOSI_Pin                       GPIO_PIN_7
#define MX_SPI1_MOSI_Port                      GPIOD
#define MX_SPI1_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI1_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Alternate                 GPIO_AF5_SPI1

/* SPI1_MISO */
#define MX_SPI1_MISO                           PG9
#define MX_SPI1_MISO_Pin                       GPIO_PIN_9
#define MX_SPI1_MISO_Port                      GPIOG
#define MX_SPI1_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI1_MISO_Pull                      GPIO_NOPULL
#define MX_SPI1_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MISO_Alternate                 GPIO_AF5_SPI1

/*------------------------------ UART4          -----------------------------*/
#define MX_UART4                               1

/* Pins */

/* UART4_RX */
#define MX_UART4_RX                            PD0
#define MX_UART4_RX_Pin                        GPIO_PIN_0
#define MX_UART4_RX_Port                       GPIOD
#define MX_UART4_RX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_RX_Pull                       GPIO_NOPULL
#define MX_UART4_RX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_RX_Alternate                  GPIO_AF8_UART4

/* UART4_TX */
#define MX_UART4_TX                            PD1
#define MX_UART4_TX_Pin                        GPIO_PIN_1
#define MX_UART4_TX_Port                       GPIOD
#define MX_UART4_TX_Mode                       GPIO_MODE_AF_PP
#define MX_UART4_TX_Pull                       GPIO_NOPULL
#define MX_UART4_TX_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_UART4_TX_Alternate                  GPIO_AF8_UART4

/*------------------------------ ETH            -----------------------------*/
#define MX_ETH                                 1

/* Pins */

/* ETH_RX_CLK */
#define MX_ETH_RX_CLK                          PA1
#define MX_ETH_RX_CLK_Pin                      GPIO_PIN_1
#define MX_ETH_RX_CLK_Port                     GPIOA
#define MX_ETH_RX_CLK_Mode                     GPIO_MODE_AF_PP
#define MX_ETH_RX_CLK_Pull                     GPIO_NOPULL
#define MX_ETH_RX_CLK_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_ETH_RX_CLK_Alternate                GPIO_AF11_ETH

/* ETH_MDIO */
#define MX_ETH_MDIO                            PA2
#define MX_ETH_MDIO_Pin                        GPIO_PIN_2
#define MX_ETH_MDIO_Port                       GPIOA
#define MX_ETH_MDIO_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_MDIO_Pull                       GPIO_NOPULL
#define MX_ETH_MDIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDIO_Alternate                  GPIO_AF11_ETH

/* ETH_RX_DV */
#define MX_ETH_RX_DV                           PA7
#define MX_ETH_RX_DV_Pin                       GPIO_PIN_7
#define MX_ETH_RX_DV_Port                      GPIOA
#define MX_ETH_RX_DV_Mode                      GPIO_MODE_AF_PP
#define MX_ETH_RX_DV_Pull                      GPIO_NOPULL
#define MX_ETH_RX_DV_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_ETH_RX_DV_Alternate                 GPIO_AF11_ETH

/* ETH_RXD3 */
#define MX_ETH_RXD3                            PB1
#define MX_ETH_RXD3_Pin                        GPIO_PIN_1
#define MX_ETH_RXD3_Port                       GPIOB
#define MX_ETH_RXD3_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD3_Pull                       GPIO_NOPULL
#define MX_ETH_RXD3_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD3_Alternate                  GPIO_AF11_ETH

/* ETH_MDC */
#define MX_ETH_MDC                             PC1
#define MX_ETH_MDC_Pin                         GPIO_PIN_1
#define MX_ETH_MDC_Port                        GPIOC
#define MX_ETH_MDC_Mode                        GPIO_MODE_AF_PP
#define MX_ETH_MDC_Pull                        GPIO_NOPULL
#define MX_ETH_MDC_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDC_Alternate                   GPIO_AF11_ETH

/* ETH_TXD2 */
#define MX_ETH_TXD2                            PC2
#define MX_ETH_TXD2_Pin                        GPIO_PIN_2
#define MX_ETH_TXD2_Port                       GPIOC
#define MX_ETH_TXD2_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD2_Pull                       GPIO_NOPULL
#define MX_ETH_TXD2_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD2_Alternate                  GPIO_AF11_ETH

/* ETH_TX_CLK */
#define MX_ETH_TX_CLK                          PC3
#define MX_ETH_TX_CLK_Pin                      GPIO_PIN_3
#define MX_ETH_TX_CLK_Port                     GPIOC
#define MX_ETH_TX_CLK_Mode                     GPIO_MODE_AF_PP
#define MX_ETH_TX_CLK_Pull                     GPIO_NOPULL
#define MX_ETH_TX_CLK_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_ETH_TX_CLK_Alternate                GPIO_AF11_ETH

/* ETH_RXD0 */
#define MX_ETH_RXD0                            PC4
#define MX_ETH_RXD0_Pin                        GPIO_PIN_4
#define MX_ETH_RXD0_Port                       GPIOC
#define MX_ETH_RXD0_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD0_Pull                       GPIO_NOPULL
#define MX_ETH_RXD0_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD0_Alternate                  GPIO_AF11_ETH

/* ETH_RXD1 */
#define MX_ETH_RXD1                            PC5
#define MX_ETH_RXD1_Pin                        GPIO_PIN_5
#define MX_ETH_RXD1_Port                       GPIOC
#define MX_ETH_RXD1_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD1_Pull                       GPIO_NOPULL
#define MX_ETH_RXD1_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD1_Alternate                  GPIO_AF11_ETH

/* ETH_TXD3 */
#define MX_ETH_TXD3                            PE2
#define MX_ETH_TXD3_Pin                        GPIO_PIN_2
#define MX_ETH_TXD3_Port                       GPIOE
#define MX_ETH_TXD3_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD3_Pull                       GPIO_NOPULL
#define MX_ETH_TXD3_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD3_Alternate                  GPIO_AF11_ETH

/* ETH_TX_EN */
#define MX_ETH_TX_EN                           PG11
#define MX_ETH_TX_EN_Pin                       GPIO_PIN_11
#define MX_ETH_TX_EN_Port                      GPIOG
#define MX_ETH_TX_EN_Mode                      GPIO_MODE_AF_PP
#define MX_ETH_TX_EN_Pull                      GPIO_NOPULL
#define MX_ETH_TX_EN_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_ETH_TX_EN_Alternate                 GPIO_AF11_ETH

/* ETH_TXD1 */
#define MX_ETH_TXD1                            PG12
#define MX_ETH_TXD1_Pin                        GPIO_PIN_12
#define MX_ETH_TXD1_Port                       GPIOG
#define MX_ETH_TXD1_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD1_Pull                       GPIO_NOPULL
#define MX_ETH_TXD1_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD1_Alternate                  GPIO_AF11_ETH

/* ETH_TXD0 */
#define MX_ETH_TXD0                            PG13
#define MX_ETH_TXD0_Pin                        GPIO_PIN_13
#define MX_ETH_TXD0_Port                       GPIOG
#define MX_ETH_TXD0_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_TXD0_Pull                       GPIO_NOPULL
#define MX_ETH_TXD0_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD0_Alternate                  GPIO_AF11_ETH

/* ETH_CRS */
#define MX_ETH_CRS                             PH2
#define MX_ETH_CRS_Pin                         GPIO_PIN_2
#define MX_ETH_CRS_Port                        GPIOH
#define MX_ETH_CRS_Mode                        GPIO_MODE_AF_PP
#define MX_ETH_CRS_Pull                        GPIO_NOPULL
#define MX_ETH_CRS_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_ETH_CRS_Alternate                   GPIO_AF11_ETH

/* ETH_COL */
#define MX_ETH_COL                             PH3
#define MX_ETH_COL_Pin                         GPIO_PIN_3
#define MX_ETH_COL_Port                        GPIOH
#define MX_ETH_COL_Mode                        GPIO_MODE_AF_PP
#define MX_ETH_COL_Pull                        GPIO_NOPULL
#define MX_ETH_COL_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_ETH_COL_Alternate                   GPIO_AF11_ETH

/* ETH_RXD2 */
#define MX_ETH_RXD2                            PH6
#define MX_ETH_RXD2_Pin                        GPIO_PIN_6
#define MX_ETH_RXD2_Port                       GPIOH
#define MX_ETH_RXD2_Mode                       GPIO_MODE_AF_PP
#define MX_ETH_RXD2_Pull                       GPIO_NOPULL
#define MX_ETH_RXD2_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD2_Alternate                  GPIO_AF11_ETH

/*------------------------------ USART2         -----------------------------*/
#define MX_USART2                              1

/* Virtual mode */
#define MX_USART2_VM                           VM_ASYNC

/* Pins */

/* USART2_RX */
#define MX_USART2_RX                           PA3
#define MX_USART2_RX_Pin                       GPIO_PIN_3
#define MX_USART2_RX_Port                      GPIOA
#define MX_USART2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_RX_Pull                      GPIO_NOPULL
#define MX_USART2_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Alternate                 GPIO_AF7_USART2

/* USART2_TX */
#define MX_USART2_TX                           PD5
#define MX_USART2_TX_Pin                       GPIO_PIN_5
#define MX_USART2_TX_Port                      GPIOD
#define MX_USART2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_TX_Pull                      GPIO_NOPULL
#define MX_USART2_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Alternate                 GPIO_AF7_USART2

/*------------------------------ USART3         -----------------------------*/
#define MX_USART3                              1

/* Virtual mode */
#define MX_USART3_VM                           VM_ASYNC

/* Pins */

/* USART3_TX */
#define MX_USART3_TX                           PB10
#define MX_USART3_TX_Pin                       GPIO_PIN_10
#define MX_USART3_TX_Port                      GPIOB
#define MX_USART3_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_TX_Pull                      GPIO_NOPULL
#define MX_USART3_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART3_TX_Alternate                 GPIO_AF7_USART3

/* USART3_RX */
#define MX_USART3_RX                           PB11
#define MX_USART3_RX_Pin                       GPIO_PIN_11
#define MX_USART3_RX_Port                      GPIOB
#define MX_USART3_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART3_RX_Pull                      GPIO_NOPULL
#define MX_USART3_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART3_RX_Alternate                 GPIO_AF7_USART3

/*------------------------------ USB_OTG_FS     -----------------------------*/
#define MX_USB_OTG_FS                          1

/* Virtual mode */
#define MX_USB_OTG_FS_VM                       Host_Only

/* Pins */

/* USB_OTG_FS_DM */
#define MX_USB_OTG_FS_DM                       PA11
#define MX_USB_OTG_FS_DM_Pin                   GPIO_PIN_11
#define MX_USB_OTG_FS_DM_Port                  GPIOA
#define MX_USB_OTG_FS_DM_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DM_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DM_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USB_OTG_FS_DM_Alternate             GPIO_AF10_OTG1_FS

/* USB_OTG_FS_DP */
#define MX_USB_OTG_FS_DP                       PA12
#define MX_USB_OTG_FS_DP_Pin                   GPIO_PIN_12
#define MX_USB_OTG_FS_DP_Port                  GPIOA
#define MX_USB_OTG_FS_DP_Mode                  GPIO_MODE_AF_PP
#define MX_USB_OTG_FS_DP_Pull                  GPIO_NOPULL
#define MX_USB_OTG_FS_DP_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USB_OTG_FS_DP_Alternate             GPIO_AF10_OTG1_FS

/*------------------------------ FDCAN1         -----------------------------*/
#define MX_FDCAN1                              1

/* Pins */

/* FDCAN1_TX */
#define MX_FDCAN1_TX                           PH13
#define MX_FDCAN1_TX_Pin                       GPIO_PIN_13
#define MX_FDCAN1_TX_Port                      GPIOH
#define MX_FDCAN1_TX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_TX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_TX_Alternate                 GPIO_AF9_FDCAN1

/* FDCAN1_RX */
#define MX_FDCAN1_RX                           PH14
#define MX_FDCAN1_RX_Pin                       GPIO_PIN_14
#define MX_FDCAN1_RX_Port                      GPIOH
#define MX_FDCAN1_RX_Mode                      GPIO_MODE_AF_PP
#define MX_FDCAN1_RX_Pull                      GPIO_NOPULL
#define MX_FDCAN1_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_RX_Alternate                 GPIO_AF9_FDCAN1

/*------------------------------ FDCAN2         -----------------------------*/
#define MX_FDCAN2                              1

/* Pins */

/* FDCAN2_TX */
#define MX_FDCAN2_TX                           PB13

/* FDCAN2_RX */
#define MX_FDCAN2_RX                           PB5

/*------------------------------ I2C1           -----------------------------*/
#define MX_I2C1                                1

/* Pins */

/* I2C1_SCL */
#define MX_I2C1_SCL                            PB6
#define MX_I2C1_SCL_Pin                        GPIO_PIN_6
#define MX_I2C1_SCL_Port                       GPIOB
#define MX_I2C1_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SCL_Pull                       GPIO_NOPULL
#define MX_I2C1_SCL_Speed                      GPIO_SPEED_FREQ_HIGH
#define MX_I2C1_SCL_Alternate                  GPIO_AF4_I2C1

/* I2C1_SDA */
#define MX_I2C1_SDA                            PB7
#define MX_I2C1_SDA_Pin                        GPIO_PIN_7
#define MX_I2C1_SDA_Port                       GPIOB
#define MX_I2C1_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C1_SDA_Pull                       GPIO_PULLUP
#define MX_I2C1_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C1_SDA_Alternate                  GPIO_AF4_I2C1

/*------------------------------ I2C3           -----------------------------*/
#define MX_I2C3                                1

/* Pins */

/* I2C3_SCL */
#define MX_I2C3_SCL                            PH7
#define MX_I2C3_SCL_Pin                        GPIO_PIN_7
#define MX_I2C3_SCL_Port                       GPIOH
#define MX_I2C3_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SCL_Pull                       GPIO_NOPULL
#define MX_I2C3_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SCL_Alternate                  GPIO_AF4_I2C3

/* I2C3_SDA */
#define MX_I2C3_SDA                            PH8
#define MX_I2C3_SDA_Pin                        GPIO_PIN_8
#define MX_I2C3_SDA_Port                       GPIOH
#define MX_I2C3_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SDA_Pull                       GPIO_NOPULL
#define MX_I2C3_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SDA_Alternate                  GPIO_AF4_I2C3

/*------------------------------ LPUART1        -----------------------------*/
#define MX_LPUART1                             1

/* Pins */

/* LPUART1_RX */
#define MX_LPUART1_RX                          PA10
#define MX_LPUART1_RX_Pin                      GPIO_PIN_10
#define MX_LPUART1_RX_Port                     GPIOA
#define MX_LPUART1_RX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_RX_Pull                     GPIO_NOPULL
#define MX_LPUART1_RX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Alternate                GPIO_AF3_LPUART

/* LPUART1_TX */
#define MX_LPUART1_TX                          PA9
#define MX_LPUART1_TX_Pin                      GPIO_PIN_9
#define MX_LPUART1_TX_Port                     GPIOA
#define MX_LPUART1_TX_Mode                     GPIO_MODE_AF_PP
#define MX_LPUART1_TX_Pull                     GPIO_NOPULL
#define MX_LPUART1_TX_Speed                    GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Alternate                GPIO_AF3_LPUART

#endif  /* __MX_DEVICE_H */
