/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/12/2023 15:45:05
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/
 
 #ifndef __MX_DEVICE_H
 #define __MX_DEVICE_H
   
 
/*------------------------------ SPI3           -----------------------------*/
#define MX_SPI3                                1

/* Pins */

/* SPI3_SCK */
#define MX_SPI3_SCK                            PA0
#define MX_SPI3_SCK_Pin                        GPIO_PIN_0
#define MX_SPI3_SCK_Port                       GPIOA
#define MX_SPI3_SCK_Mode                       GPIO_MODE_AF_PP
#define MX_SPI3_SCK_Pull                       GPIO_NOPULL
#define MX_SPI3_SCK_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_SPI3_SCK_Alternate                  GPIO_AF6_SPI3

/* SPI3_MOSI */
#define MX_SPI3_MOSI                           PB8
#define MX_SPI3_MOSI_Pin                       GPIO_PIN_8
#define MX_SPI3_MOSI_Port                      GPIOB
#define MX_SPI3_MOSI_Mode                      GPIO_MODE_AF_PP
#define MX_SPI3_MOSI_Pull                      GPIO_NOPULL
#define MX_SPI3_MOSI_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI3_MOSI_Alternate                 GPIO_AF6_SPI3

/* SPI3_MISO */
#define MX_SPI3_MISO                           PB9
#define MX_SPI3_MISO_Pin                       GPIO_PIN_9
#define MX_SPI3_MISO_Port                      GPIOB
#define MX_SPI3_MISO_Mode                      GPIO_MODE_AF_PP
#define MX_SPI3_MISO_Pull                      GPIO_NOPULL
#define MX_SPI3_MISO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_SPI3_MISO_Alternate                 GPIO_AF6_SPI3

/*------------------------------ USART2         -----------------------------*/
#define MX_USART2                              1

/* Virtual mode */
#define MX_USART2_VM                           VM_ASYNC

/* Pins */

/* USART2_RX */
#define MX_USART2_RX                           PA11
#define MX_USART2_RX_Pin                       GPIO_PIN_11
#define MX_USART2_RX_Port                      GPIOA
#define MX_USART2_RX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_RX_Pull                      GPIO_NOPULL
#define MX_USART2_RX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Alternate                 GPIO_AF3_USART2

/* USART2_TX */
#define MX_USART2_TX                           PA14
#define MX_USART2_TX_Pin                       GPIO_PIN_14
#define MX_USART2_TX_Port                      GPIOA
#define MX_USART2_TX_Mode                      GPIO_MODE_AF_PP
#define MX_USART2_TX_Pull                      GPIO_NOPULL
#define MX_USART2_TX_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Alternate                 GPIO_AF3_USART2

/*------------------------------ I2C3           -----------------------------*/
#define MX_I2C3                                1

/* Pins */

/* I2C3_SCL */
#define MX_I2C3_SCL                            PA6
#define MX_I2C3_SCL_Pin                        GPIO_PIN_6
#define MX_I2C3_SCL_Port                       GPIOA
#define MX_I2C3_SCL_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SCL_Pull                       GPIO_NOPULL
#define MX_I2C3_SCL_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SCL_Alternate                  GPIO_AF4_I2C3

/* I2C3_SDA */
#define MX_I2C3_SDA                            PA7
#define MX_I2C3_SDA_Pin                        GPIO_PIN_7
#define MX_I2C3_SDA_Port                       GPIOA
#define MX_I2C3_SDA_Mode                       GPIO_MODE_AF_OD
#define MX_I2C3_SDA_Pull                       GPIO_NOPULL
#define MX_I2C3_SDA_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_I2C3_SDA_Alternate                  GPIO_AF4_I2C3

#endif  /* __MX_DEVICE_H */
